MERGE dbo.Airline AS TARGET
USING (VALUES ('A3', 'AEE', 'ALEGEAN',         'GR', 1, 'Aegean Airlines'),
              ('EI', 'EIN', 'SHAMROCK',        'IE', 1, 'Aer Lingus'),
              ('AM', 'AMX', 'AEROMEXICO',      'MX', 1, 'Aeroméxico'),
              ('AH', 'DAH', 'AIR ALGERIE',     'DZ', 1, 'Air Algérie'),
              ('KC', 'KZR', 'ASTANALINE',      'KZ', 1, 'Air Astana'),
              ('BT', 'BTI', 'AIRBALTIC',       'LV', 1, 'Air Baltic'),
              ('AC', 'ACA', 'AIR CANADA',      'CA', 1, 'Air Canada'),
              ('CA', 'CCA', 'AIR CHINA',       'CN', 1, 'Air China'),
              ('AF', 'AFT', 'AIRFRANS',        'FR', 1, 'Air France'),
              ('AI', 'AIC', 'AIRINDIA',        'IN', 1, 'Air India Limited'),
              ('KM', 'AMC', 'AIR MALTA',       'MT', 1, 'Air Malta'),
              ('JU', 'ASL', 'AIR SERBIA',      'RS', 1, 'Air Serbia'),
              ('NH', 'ANA', 'ALL NIPPON',      'JP', 1, 'All Nippon Airways'),
              ('AA', 'AAL', 'AMERICAN',        'US', 1, 'American Airlines'),
              ('OZ', 'AAR', 'ASIANA',          'KR', 1, 'Asiana Airlines'),
              ('OS', 'AUA', 'AUSTRIAN',        'AT', 1, 'Austrian Airlines'),
              ('AV', 'AVA', 'AVIANCA',         'CO', 1, 'Avianca'),
              ('J2', 'AHY', 'AZAL',            'AZ', 1, 'Azerbaijan Airlines'),
              ('BG', 'BBC', 'BANGLADASH',      'BD', 1, 'Biman Bangladesh Airlines'),
              ('BA', 'BAW', 'SPEEDBIRD',       'GB', 1, 'British Airways'),
              ('SN', 'BXI', 'XENIA',           'BE', 1, 'Brussels Airlines'),
              ('FB', 'LZB', 'FLYING BULGARIA', 'BG', 1, 'Bulgaria Air'),
              ('CX', 'CPA', 'CATHAY',          'HK', 1, 'Cathay Pacific'),
              ('CI', 'CAL', 'DYNASTY',         'CN', 1, 'China Airlines'),
              ('MU', 'CES', 'CHINA EASTERN',   'CN', 1, 'China Eastern Airlines'),
              ('CZ', 'CSN', 'CHINA SOUTHERN',  'CN', 1, 'China Southern Airlines'),
              ('OU', 'CTN', 'CROATIA',         'HR', 1, 'Croatia Airlines'),
              ('DL', 'DAL', 'DELTA',           'US', 1, 'Delta Air Lines'),
              ('MS', 'MSR', 'EGYPTAIR',        'EG', 1, 'Egyptair'),
              ('LY', 'ELY', 'ELAL',            'IL', 1, 'El Al Israel Airlines'),
              ('EK', 'UAE', 'EMIRATES',        'AE', 1, 'Emirates'),
              ('ET', 'ETH', 'ETHIOPIAN',       'ET', 1, 'Ethiopian Airlines'),
              ('EY', 'ETD', 'ETHIDAD',         'AE', 1, 'Etihad Airways'),
              ('EW', 'RWG', 'EUROWINGS',       'DE', 1, 'Eurowings'),
              ('BR', 'EVA', 'EVA',             'TW', 1, 'Eva Air'),
              ('AY', 'FIN', 'FINNAIR',         'FI', 1, 'Finnair'),
              ('GF', 'GFA', 'GULF AIR',        'BH', 1, 'Gulf Air'),
              ('HU', 'CHN', 'HAINAN',          'CN', 1, 'Hainan Airlines'),
              ('IB', 'IBE', 'IBERIA',          'ES', 1, 'Iberia'),
              ('FI', 'ICE', 'ICEAIR',          'IS', 1, 'Icelandair'),
              ('IR', 'IRA', 'IRANAIR',         'IR', 1, 'Iran Air'),
              ('AZ', 'ITY', 'ITARROW',         'IT', 1, 'ITA Airways'),
              ('JL', 'JAL', 'JAPANAIR',        'JP', 1, 'Japan Airlines'),
              ('B6', 'JBU', 'JETBLUE',         'US', 1, 'JetBlue Airways'),
              ('KQ', 'KQA', 'KENYA',           'KE', 1, 'Kenya Airways'),
              ('KL', 'KLM', 'KLM',             'NL', 1, 'KLM'),
              ('KE', 'KAL', 'KOREANAIR',       'KR', 1, 'Korean Air'),
              ('KU', 'KAC', 'KUWAITI',         'KW', 1, 'Kuwait Airways'),
              ('LA', 'LAN', 'LAN CHILE',       'CL', 1, 'Latam Chile'),
              ('LM', 'LOG', 'LOGAN',           'GB', 1, 'Loganair'),
              ('LO', 'LOT', 'POLLOT',          'PL', 1, 'LOT Polish Airlines'),
              ('LH', 'DLH', 'LUFTHANSA',       'DE', 1, 'Lufthansa'),
              ('MH', 'MAS', 'MALAYSIAN',       'MY', 1, 'Malaysia Airlines'),
              ('ME', 'MEA', 'CEDAR JET',       'LB', 1, 'Middle East Airlines'),
              ('WY', 'OMA', 'OMAN AIR',        'OM', 1, 'Oman Air'),
              ('QF', 'QFA', 'QANTAS',          'AT', 1, 'Qantas'),
              ('QR', 'QTR', 'QATARI',          'QA', 1, 'Qatar Airways'),
              ('AT', 'RAM', 'ROYALAIR MAROC',  'MA', 1, 'Royal Air Maroc'),
              ('BI', 'RBA', 'BRUNEI',          'BN', 1, 'Royal Brunei Airlines'),
              ('RJ', 'RJA', 'JORDANIAN',       'JO', 1, 'Royal Jordanian'),
              ('WB', 'RWD', 'RWANDAIR',        'RW', 1, 'RwandAir'),
              ('SK', 'SAS', 'SCANDIANAVIAN',   'SE', 1, 'SAS Scandinavian Airlines'),
              ('SV', 'SVA', 'SAUDIA',          'SA', 1, 'Saudia'),
              ('ZH', 'CSV', 'SHENZHEN AIR',    'CN', 1, 'Shenzhen Airlines'),
              ('SQ', 'SIA', 'SINGAPORE',       'SG', 1, 'Singapore Airlines'),
              ('UL', 'ALK', 'SRILANKAN',       'LK', 1, 'Srilankan Airlines'),
              ('LX', 'SWR', 'SWISS',           'CH', 1, 'Swiss'),
              ('TP', 'TAP', 'AIR PORTUGAL',    'PT', 1, 'TAP Portugal'),
              ('RO', 'ROT', 'TAROM',           'RO', 1, 'Tarom'),
              ('TG', 'THA', 'THAI',            'TH', 1, 'Thai Airways International'),
              ('GS', 'GCR', 'BO HAI',          'CN', 1, 'Tianjin Airlines'),
              ('TU', 'TAR', 'TUNAIR',          'TN', 1, 'TunisAir'),
              ('TK', 'THY', 'TURKISH',         'TR', 1, 'Turkish Airlines'),
              ('T5', 'TUA', 'TURKMENISTAN',    'TM', 1, 'Turkmenistan Airlines'),
              ('UA', 'UAL', 'UNITED',          'US', 1, 'United Airlines'),
              ('HY', 'UZB', 'UZBEK',           'UZ', 1, 'Uzbekistan Airways'),
              ('VN', 'HVN', 'VIET NAM',        'VN', 1, 'Vietnam Airlines'),
              ('VS', 'VIR', 'VIRGIN',          'GB', 1, 'Virgin Atlantic'),
              ('UK', 'VTI', 'VISTARA',         'IN', 1, 'Vistara'),
              ('WS', 'WJA', 'WESTJET',         'CA', 1, 'WestJet'))
AS SOURCE (IATACode, ICAOCode, Callsign, CountryCode, IsActive, AirlineName)
ON TARGET.IATACode = SOURCE.IATACode
WHEN MATCHED THEN UPDATE SET TARGET.ICAOCode    = SOURCE.ICAOCode,
                             TARGET.Callsign    = SOURCE.Callsign,
                             TARGET.CountryCode = SOURCE.CountryCode,
                             TARGET.IsActive    = SOURCE.IsActive,
                             TARGET.AirlineName = SOURCE.AirlineName
WHEN NOT MATCHED BY TARGET THEN INSERT (IATACode,
                                        ICAOCode,
                                        Callsign,
                                        CountryCode,
                                        IsActive,
                                        AirlineName)
                                VALUES (SOURCE.IATACode,
                                        SOURCE.ICAOCode,
                                        SOURCE.Callsign,
                                        SOURCE.CountryCode,
                                        SOURCE.IsActive,
                                        SOURCE.AirlineName)
WHEN NOT MATCHED BY SOURCE THEN DELETE;