// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaleLearnCode.FlightTrackingDemo.SqlData.Models;

/// <summary>
/// Lookup table representing the daily flight schedule.
/// </summary>
public partial class FlightSchedule
{
    /// <summary>
    /// Identifier of the scheduled daily flight.
    /// </summary>
    public string FlightScheduleCode { get; set; }

    /// <summary>
    /// The IATA code of the airline operating the flight.
    /// </summary>
    public string AirlineCode { get; set; }

    /// <summary>
    /// The flight number for the scheduled flight.
    /// </summary>
    public string FlightNumber { get; set; }

    /// <summary>
    /// The IATA code of the airport where the flight departs.
    /// </summary>
    public string DepartureAirportCode { get; set; }

    /// <summary>
    /// The IATA code of the airport where the flight arrives.
    /// </summary>
    public string ArrivalAirportCode { get; set; }

    /// <summary>
    /// The time of day when the flight departs.
    /// </summary>
    public TimeOnly DepartureTime { get; set; }

    /// <summary>
    /// The time of day when the flight arrives.
    /// </summary>
    public TimeOnly ArrivalTime { get; set; }

    /// <summary>
    /// The duration of the flight in minutes.
    /// </summary>
    public int FlightTime { get; set; }

    /// <summary>
    /// The type of aircraft used for the flight.
    /// </summary>
    public string AircraftTypeCode { get; set; }

    public virtual AircraftType AircraftTypeCodeNavigation { get; set; }

    public virtual Airline AirlineCodeNavigation { get; set; }

    public virtual Airport ArrivalAirportCodeNavigation { get; set; }

    public virtual Airport DepartureAirportCodeNavigation { get; set; }
}