// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaleLearnCode.FlightTrackingDemo.SqlData.Models;

/// <summary>
/// Lookup table of the different status of a flight.
/// </summary>
public partial class FlightStatus
{
    /// <summary>
    /// The code for the flight status.
    /// </summary>
    public string FlightStatusCode { get; set; }

    /// <summary>
    /// The name of the flight status.
    /// </summary>
    public string FlightStatusName { get; set; }

    /// <summary>
    /// The description of the flight status.
    /// </summary>
    public string FlightStatusDescription { get; set; }

    public virtual ICollection<CustomerFlightStatusToFlightStatus> CustomerFlightStatusToFlightStatuses { get; set; } = new List<CustomerFlightStatusToFlightStatus>();

    public virtual ICollection<FlightPlan> FlightPlans { get; set; } = new List<FlightPlan>();

    public virtual ICollection<FlightTelemetry> FlightTelemetries { get; set; } = new List<FlightTelemetry>();

    public virtual ICollection<Telemetry> Telemetries { get; set; } = new List<Telemetry>();
}