// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaleLearnCode.FlightTrackingDemo.SqlData.Models;

/// <summary>
/// Table to store the fuel system data for a flight.
/// </summary>
public partial class TelemetryFuelSystemDatum
{
    /// <summary>
    /// Identifier of the fuel system data for a flight.
    /// </summary>
    public long TelemetryFuelSystemDataId { get; set; }

    /// <summary>
    /// Identifier of the Telemetry data for a flight.
    /// </summary>
    public Guid FlightTelemetryId { get; set; }

    /// <summary>
    /// The quantity of fuel in the fuel system in liters.
    /// </summary>
    public double? FuelQuantity { get; set; }

    /// <summary>
    /// The rate of fuel consumption in liters per hour.
    /// </summary>
    public double? FuelConsumptionRate { get; set; }

    /// <summary>
    /// Indicates if the fuel system data is incomplete.
    /// </summary>
    public bool? IsIncomplete { get; set; }

    public virtual Telemetry FlightTelemetry { get; set; }

    public virtual ICollection<TelemetryFuelTankLevel> TelemetryFuelTankLevels { get; set; } = new List<TelemetryFuelTankLevel>();
}