// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaleLearnCode.FlightTrackingDemo.SqlData.Models;

/// <summary>
/// Table to store the flight parameters data for a flight.
/// </summary>
public partial class TelemetryFlightParameter
{
    /// <summary>
    /// Identifier of the flight parameter record.
    /// </summary>
    public long TelemetryFlightParameterId { get; set; }

    /// <summary>
    /// Identifier of the Telemetry data for a flight.
    /// </summary>
    public Guid FlightTelemetryId { get; set; }

    /// <summary>
    /// The time of the flight in milliseconds.
    /// </summary>
    public int? FlightTime { get; set; }

    /// <summary>
    /// The altitude of the aircraft at the time of the Telemetry data.
    /// </summary>
    public int? Altitude { get; set; }

    /// <summary>
    /// The vertical speed of the aircraft at the time of the Telemetry data.
    /// </summary>
    public double? VerticalSpeed { get; set; }

    /// <summary>
    /// The heading of the aircraft at the time of the Telemetry data.
    /// </summary>
    public double? Heading { get; set; }

    /// <summary>
    /// The pitch of the aircraft at the time of the Telemetry data.
    /// </summary>
    public double? Pitch { get; set; }

    /// <summary>
    /// The roll of the aircraft at the time of the Telemetry data.
    /// </summary>
    public double? Roll { get; set; }

    /// <summary>
    /// The yaw of the aircraft at the time of the Telemetry data.
    /// </summary>
    public double? Yaw { get; set; }

    /// <summary>
    /// Indicates if the flight parameters data is incomplete.
    /// </summary>
    public bool? IsIncomplete { get; set; }

    public virtual Telemetry FlightTelemetry { get; set; }
}