// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaleLearnCode.FlightTrackingDemo.SqlData.Models;

/// <summary>
/// Table to store the fault codes for an electrical system data record.
/// </summary>
public partial class TelemetryElectricalSystemFault
{
    /// <summary>
    /// Identifier of the fault code for an electrical system data record.
    /// </summary>
    public long TelemetryElectricalSystemFaultId { get; set; }

    /// <summary>
    /// Identifier of the electrical system data for a flight.
    /// </summary>
    public long TelemetryElectricalSystemId { get; set; }

    /// <summary>
    /// The fault code for an electrical system data record.
    /// </summary>
    public string FaultCode { get; set; }

    public virtual TelemetryElectricalSystem TelemetryElectricalSystem { get; set; }
}