// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaleLearnCode.FlightTrackingDemo.SqlData.Models;

/// <summary>
/// Table to store the hydraulic system data for a flight.
/// </summary>
public partial class TelemetryHydraulicSystem
{
    /// <summary>
    /// Identifier of the hydraulic system data for a flight.
    /// </summary>
    public long TelemetryHydraulicSystemId { get; set; }

    /// <summary>
    /// Identifier of the Telemetry data for a flight.
    /// </summary>
    public Guid FlightTelemetryId { get; set; }

    /// <summary>
    /// The pressure of the hydraulic system in psi.
    /// </summary>
    public double? HydraulicPressure { get; set; }

    /// <summary>
    /// The status of the actuators in the hydraulic system.
    /// </summary>
    public string ActuatorStatus { get; set; }

    /// <summary>
    /// Indicates if the hydraulic system data is incomplete.
    /// </summary>
    public bool? IsIncomplete { get; set; }

    public virtual Telemetry FlightTelemetry { get; set; }

    public virtual ICollection<TelemetryHydraulicSystemFluidLevel> TelemetryHydraulicSystemFluidLevels { get; set; } = new List<TelemetryHydraulicSystemFluidLevel>();
}