// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaleLearnCode.FlightTrackingDemo.SqlData.Models;

/// <summary>
/// Table to store the fault codes for an engine data record.
/// </summary>
public partial class TelemetryEngineDataFaultCode
{
    /// <summary>
    /// Identifier of the fault code for an engine data record.
    /// </summary>
    public long TelemetryEngineDataFaultCodeId { get; set; }

    /// <summary>
    /// Identifier of the engine data for a flight.
    /// </summary>
    public long TelemetryEngineDataId { get; set; }

    /// <summary>
    /// The fault code for an engine data record.
    /// </summary>
    public string FaultCode { get; set; }

    public virtual TelemetryEngineDatum TelemetryEngineData { get; set; }
}