// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaleLearnCode.FlightTrackingDemo.SqlData.Models;

/// <summary>
/// Table to store the electrical system data for a flight.
/// </summary>
public partial class TelemetryElectricalSystem
{
    /// <summary>
    /// Identifier of the electrical system data for a flight.
    /// </summary>
    public long TeleElectricalSystemId { get; set; }

    /// <summary>
    /// Identifier of the Telemetry data for a flight.
    /// </summary>
    public Guid FlightTelemetryId { get; set; }

    /// <summary>
    /// The amount of power generated by the electrical system in watts.
    /// </summary>
    public double? PowerGeneration { get; set; }

    /// <summary>
    /// The distribution of power in the electrical system.
    /// </summary>
    public string PowerDistribution { get; set; }

    /// <summary>
    /// The status of the battery in the electrical system.
    /// </summary>
    public string BatteryStatus { get; set; }

    /// <summary>
    /// Indicates if the electrical system data is incomplete.
    /// </summary>
    public bool? IsIncomplete { get; set; }

    public virtual Telemetry FlightTelemetry { get; set; }

    public virtual ICollection<TelemetryElectricalSystemFault> TelemetryElectricalSystemFaults { get; set; } = new List<TelemetryElectricalSystemFault>();
}