// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaleLearnCode.FlightTrackingDemo.SqlData.Models;

/// <summary>
/// Table to store the fuel tank levels for a fuel system data record.
/// </summary>
public partial class TelemetryFuelTankLevel
{
    /// <summary>
    /// Identifier of the fuel tank level for a fuel system data record.
    /// </summary>
    public long TelemetryFuelTankLevelId { get; set; }

    /// <summary>
    /// Identifier of the fuel system data for a flight.
    /// </summary>
    public long TelemetryFuelSystemDataId { get; set; }

    /// <summary>
    /// The number of the fuel tank.
    /// </summary>
    public int TankNumber { get; set; }

    /// <summary>
    /// The level of fuel in the fuel tank in liters.
    /// </summary>
    public double FuelLevel { get; set; }

    public virtual TelemetryFuelSystemDatum TelemetryFuelSystemData { get; set; }
}