// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaleLearnCode.FlightTrackingDemo.SqlData.Models;

/// <summary>
/// Table to store the location data for a flight.
/// </summary>
public partial class TelemetryLocation
{
    /// <summary>
    /// Identifier of the location data for a flight.
    /// </summary>
    public long TelemetryLocationId { get; set; }

    /// <summary>
    /// Identifier of the Telemetry data for a flight.
    /// </summary>
    public Guid FlightTelemetryId { get; set; }

    /// <summary>
    /// The latitude of the aircraft at the time of the Telemetry data.
    /// </summary>
    public double? Latitude { get; set; }

    /// <summary>
    /// The longitude of the aircraft at the time of the Telemetry data.
    /// </summary>
    public double? Longitude { get; set; }

    /// <summary>
    /// The distance traveled in kilometers since the last Telemetry data.
    /// </summary>
    public int? DistanceSinceLastReport { get; set; }

    /// <summary>
    /// The distance traveled in kilometers since the origin of the flight.
    /// </summary>
    public int? DistanceFromOrigin { get; set; }

    /// <summary>
    /// The distance remaining in kilometers to the destination of the flight.
    /// </summary>
    public int? DistanceToDestination { get; set; }

    /// <summary>
    /// Indicates if the location data is incomplete.
    /// </summary>
    public bool? IsIncomplete { get; set; }

    public virtual Telemetry FlightTelemetry { get; set; }
}