SET IDENTITY_INSERT PM.DigitalAsset ON
GO

MERGE PM.DigitalAsset AS TARGET
USING (VALUES 
              -- Community Attribute Icons
              (   1, 1, 1,  165,  329, 'attribute-icon-1000001', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/servingplate.svg',                                        'Restaurant with Table Service'),
              (   2, 1, 1,  166,  330, 'attribute-icon-1000002', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/servingplate.svg',                                        'Bistro'),
              (   3, 1, 1,  167,  331, 'attribute-icon-1000003', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/burger.svg',                                              'Grille'),
              (   4, 1, 1,  168,  332, 'attribute-icon-1000004', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/cheerswineglasses.svg',                                   'Cocktail Lounge'),
              (   5, 1, 1,  169,  333, 'attribute-icon-1000005', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/beermug.svg',                                             'Pub'),
              (   6, 1, 1,  170,  334, 'attribute-icon-1000006', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/dining-twochairs.svg',                                    'Private Dining Room'),
              (   7, 1, 1,  171,  335, 'attribute-icon-1000007', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/beermug.svg',                                             'Sports Lounge'),
              (   8, 1, 1,  172,  336, 'attribute-icon-1000008', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/saunaheatstone.svg',                                      'Hot Tub'),
              (   9, 1, 1,  173,  337, 'attribute-icon-1000009', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/swimmingpoolladder.svg',                                  'Indoor Swimming Pool'),
              (  10, 1, 1,  174,  338, 'attribute-icon-1000010', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/swimmingpoolladder.svg',                                  'Outdoor Swimming Pool'),
              (  11, 1, 1,  175,  339, 'attribute-icon-1000011', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/swimmingpoolladder.svg',                                  'Off-Site Pool Privileges'),
              (  12, 1, 1,  176,  340, 'attribute-icon-1000012', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/car.svg',                                                 'Covered Parking'),
              (  13, 1, 1,  177,  341, 'attribute-icon-1000013', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/car.svg',                                                 'Parking Garage'),
              (  14, 1, 1,  178,  342, 'attribute-icon-1000014', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/car.svg',                                                 'Parking'),
              (  15, 1, 1,  179,  343, 'attribute-icon-1000015', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/rose.svg',                                                'Courtyard'),
              (  16, 1, 1,  180,  344, 'attribute-icon-1013588', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/dining-singleperson.svg',                                 'Outdoor Dining Space'),
              (  17, 1, 1,  181,  345, 'attribute-icon-1000017', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/fireplace.svg',                                           'Outdoor Fireplace'),
              (  18, 1, 1,  182,  346, 'attribute-icon-1000018', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/barbecuegrill.svg',                                       'Outdoor Grill'),
              (  19, 1, 1,  183,  347, 'attribute-icon-1000019', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/outdoorwalkingpath.svg',                                  'Walking Path'),
              (  20, 1, 1,  184,  348, 'attribute-icon-1000020', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/beachsunbed.svg',                                         'Patio'),
              (  21, 1, 1,  185,  349, 'attribute-icon-1000021', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/golfflag.svg',                                            'Putting Green'),
              (  22, 1, 1,  186,  350, 'attribute-icon-1000022', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/gardenplant.svg',                                         'Resident Garden'),
              (  23, 1, 1,  187,  351, 'attribute-icon-1000023', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/openbook.svg',                                            'Cognitive Learning Center'),
              (  24, 1, 1,  188,  352, 'attribute-icon-1000024', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/bookcase.svg',                                            'Library'),
              (  25, 1, 1,  189,  353, 'attribute-icon-1000025', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/media.svg',                                               'Media Room'),
              (  26, 1, 1,  190,  354, 'attribute-icon-1000026', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/moviecamera.svg',                                         'Movie Theater'),
              (  27, 1, 1,  191,  355, 'attribute-icon-1013599', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/fitnessweights.svg',                                      'Fitness Center'),
              (  28, 1, 1,  192,  356, 'attribute-icon-1000028', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/mobilityassistance.svg',                                  'Physical Therapy Center'),
              (  29, 1, 1,  193,  357, 'attribute-icon-1000029', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/bathroomhairdryer.svg',                                   'Salon'),
              (  30, 1, 1,  194,  358, 'attribute-icon-1000030', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/lotusflower.svg',                                         'Salon & Spa'),
              (  31, 1, 1,  195,  359, 'attribute-icon-1000031', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/stethoscope.svg',                                         'On-Site Physician Office Space'),
              (  32, 1, 1,  196,  360, 'attribute-icon-1000032', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/shop.svg',                                                'On-Site Sundries Shop'),
              (  33, 1, 1,  197,  361, 'attribute-icon-1000033', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/pingpongpaddle.svg',                                      'Game Room'),
              (  34, 1, 1,  198,  362, 'attribute-icon-1000034', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/monitor.svg',                                             'Computers'),
              (  35, 1, 1,  199,  363, 'attribute-icon-1013607', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/wifi.svg',                                                'Wi-Fi in Common Areas'),
              (  36, 1, 1,  200,  364, 'attribute-icon-1000036', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/wifi.svg',                                                'Wi-Fi in Apartments'),
              (  37, 1, 1,  201,  365, 'attribute-icon-1000037', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/warehousestorage.svg',                                    'Storage Units Available'),
              (  38, 1, 1,  202,  366, 'attribute-icon-1000038', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/pawprint.svg',                                            'Pet-Friendly Environment'),
              (  39, 1, 1,  203,  367, 'attribute-icon-1000039', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/twentyfourhourtime.svg',                                  '24-Hour Staff'),
              (  40, 1, 1,  204,  368, 'attribute-icon-1000040', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/brainhead.svg',                                           'Alzheimer''s and Dementia Support Group'),
              (  41, 1, 1,  205,  369, 'attribute-icon-1000041', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/customersupport.svg',                                     'Concierge Service'),
              (  42, 1, 1,  206,  370, 'attribute-icon-1000042', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/alarmbell.svg',                                           'Emergency Alert System'),
              (  43, 1, 1,  207,  371, 'attribute-icon-1000043', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/funevent.svg',                                            'Daily Educational, Social, Cultural, and Fitness Opportunities'),
              (  44, 1, 1,  208,  372, 'attribute-icon-1000044', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/asianfoodrice.svg',                                       'Locally-Inspired Cuisine'),
              (  45, 1, 1,  209,  373, 'attribute-icon-1000045', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/glutenfree.svg',                                          'Gluten-Free Meals'),
              (  46, 1, 1,  210,  374, 'attribute-icon-1000046', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/vegan.svg',                                               'Vegetarian Options'),
              (  47, 1, 1,  211,  375, 'attribute-icon-1000047', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hexagram-religion.svg',                                   'Kosher Meals'),
              (  48, 1, 1,  212,  376, 'attribute-icon-1000048', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/seasoning.svg',                                           'Low-Sodium Meals'),
              (  49, 1, 1,  213,  377, 'attribute-icon-1000049', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/servingplate.svg',                                        '3 Chef-Prepared Meals Per Day'),
              (  50, 1, 1,  214,  378, 'attribute-icon-1000050', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/servingplate.svg',                                        '3 Chef-Prepared Meals Per Day - Assisted Living'),
              (  51, 1, 1,  215,  379, 'attribute-icon-1013653', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/servingplate.svg',                                        '2 Chef-Prepared Meals Per Day - Assisted Living'),
              (  52, 1, 1,  216,  380, 'attribute-icon-1000052', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/servingplate.svg',                                        '2 Chef-Prepared Meals Per Day - Independent Living'),
              (  53, 1, 1,  217,  381, 'attribute-icon-1000053', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/servingplate.svg',                                        '1 Chef-Prepared Meal Per Day - Independent Living'),
              (  54, 1, 1,  218,  382, 'attribute-icon-1000054', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/cleaningspray.svg',                                       'Housekeeping and Linen Service'),
              (  55, 1, 1,  219,  383, 'attribute-icon-1000055', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/laundryiron.svg',                                         'Community Laundry Service'),
              (  56, 1, 1,  220,  384, 'attribute-icon-1000056', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/fitnessweights.svg',                                      'Fitness Trainer'),
              (  57, 1, 1,  221,  385, 'attribute-icon-1000057', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/mobilityassistance.svg',                                  'Massage Therapy'),
              (  58, 1, 1,  222,  386, 'attribute-icon-1000058', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/newspaper.svg',                                           'Newspaper Delivery'),
              (  59, 1, 1,  223,  387, 'attribute-icon-1000059', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/transportation.svg',                                      'Scheduled Bus and Sedan Transportation'),
              (  60, 1, 1,  224,  388, 'attribute-icon-1013632', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/transportation.svg',                                      'Scheduled Sedan Transportation'),
              (  61, 1, 1,  225,  389, 'attribute-icon-1000061', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/transportation.svg',                                      'Scheduled Bus Transportation'),
              (  62, 1, 1,  226,  390, 'attribute-icon-1000062', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/transportation.svg',                                      'Scheduled Van Transportation'),
              (  63, 1, 1,  227,  391, 'attribute-icon-1000063', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/transportation.svg',                                      'Scheduled Sedan and Van Transportation'),
              (  64, 1, 1,  228,  392, 'attribute-icon-1013636', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/transportation.svg',                                      'Scheduled Bus and Van Transportation'),
              (  65, 1, 1,  229,  393, 'attribute-icon-1013637', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/transportation.svg',                                      'Scheduled Bus, Van, and Sedan Transportation'),
              (  66, 1, 1,  230,  394, 'attribute-icon-1000066', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/teamwork.svg',                                            'Volunteer Programs'),
              (  67, 1, 1,  231,  395, 'attribute-icon-1000067', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/mobilityassistance.svg',                                  'On-Site Physical Therapy / Occupational Therapy'),
              (  68, 1, 1,  232,  396, 'attribute-icon-1000068', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/peace-religion.svg',                                      'On-Site Worship Services'),
              (  69, 1, 1,  233,  397, 'attribute-icon-1000069', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/smartlock.svg',                                           'Electronic Key Entry'),
              (  70, 1, 1,  234,  398, 'attribute-icon-1000070', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/thermometer.svg',                                         'Individual Thermostat Control'),
              (  71, 1, 1,  235,  399, 'attribute-icon-1000071', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/sofa.svg',                                                'Furnished Apartments Available'),
              (  72, 1, 1,  236,  400, 'attribute-icon-1000072', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/oven.svg',                                                'Fully-Equipped Kitchen'),
              (  73, 1, 1,  237,  401, 'attribute-icon-1000073', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/oven.svg',                                                'Kitchen or Kitchenette'),
              (  74, 1, 1,  238,  402, 'attribute-icon-1013654', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/oven.svg',                                                'Kitchenette'),
              (  75, 1, 1,  239,  403, 'attribute-icon-1000074', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/microwave.svg',                                           'Microwave'),
              (  76, 1, 1,  240,  404, 'attribute-icon-1000075', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/fridge.svg',                                              'Refrigerator'),
              (  77, 1, 1,  241,  405, 'attribute-icon-1000076', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/balcony.svg',                                             'Balcony or Patio - Select Apartments'),
              (  78, 1, 1,  242,  406, 'attribute-icon-1000077', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/closet.svg',                                              'Walk-In Closet'),
              (  79, 1, 1,  243,  407, 'attribute-icon-1000078', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/bathroomshower.svg',                                      'Walk-In Shower'),
              (  80, 1, 1,  244,  408, 'attribute-icon-1013651', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/laundrymachine.svg',                                      'Washer and Dryer - Select Apartments'),
              (  81, 1, 1,  245,  409, 'attribute-icon-1000080', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/laundrymachine.svg',                                      'Washer and Dryer Hookups - Select Apartments'),
              (  82, 1, 1,  246,  410, 'attribute-icon-1000081', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/laundrymachine.svg',                                      'Washer and Dryer'),
              (  83, 1, 1,  247,  411, 'attribute-icon-1000082', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/laundrymachine.svg',                                      'Washer and Dryer - Independent Living'),
              (  84, 1, 1,  248,  412, 'attribute-icon-1000083', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/flatscreentv.svg',                                        'Cable TV'),
              (  85, 1, 1,  249,  413, 'attribute-icon-1000084', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/lightbulb.svg',                                           'Utilities Included'),
              (  86, 1, 1,  250,  414, 'attribute-icon-1000085', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/wrench.svg',                                              'Apartment Maintenance'),
              (  87, 1, 1,  251,  415, 'attribute-icon-1013652', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/cleaningspray.svg',                                       'Housekeeping and Linen Service'),
              (  88, 1, 1,  252,  416, 'attribute-icon-1000087', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/laundryiron.svg',                                         'Personal Laundry Service'),
              (  89, 1, 1,  253,  417, 'attribute-icon-1020000', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-oven.svg',                                            'Full Kitchen in Units'),
              (  90, 1, 1,  254,  418, 'attribute-icon-1020001', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-oven.svg',                                            'Kitchenette in Units'),
              (  91, 1, 1,  255,  419, 'attribute-icon-1020002', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-fridge.svg',                                          'Refrigerator'),
              (  92, 1, 1,  256,  420, 'attribute-icon-1020003', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-balcony.svg',                                         'Patio or Balcony'),
              (  93, 1, 1,  257,  421, 'attribute-icon-1020004', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-laundry.svg',                                         'Washer and Dryer'),
              (  94, 1, 1,  258,  422, 'attribute-icon-1020005', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-laundry.svg',                                         'Washer and Dryer Hookups'),
              (  95, 1, 1,  259,  423, 'attribute-icon-1020006', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-hanger.svg',                                          'Walk-in Closet'),
              (  96, 1, 1,  260,  424, 'attribute-icon-1020007', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-shower.svg',                                          'Walk-in Tub'),
              (  97, 1, 1,  261,  425, 'attribute-icon-1020008', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-wifi.svg',                                            'WiFi in Apartments'),
              (  98, 1, 1,  262,  426, 'attribute-icon-1020009', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-tv.svg',                                              'Basic Cable TV'),
              (  99, 1, 1,  263,  427, 'attribute-icon-1020010', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-phone.svg',                                           'Telephone Hookups'),
              ( 100, 1, 1,  264,  428, 'attribute-icon-1020011', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-cleaning-vacuum.svg',                                 'Carpet and Window Treatments'),
              ( 101, 1, 1,  265,  429, 'attribute-icon-1020012', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-hvac.svg',                                            'Individually Controlled Heating and Air Conditioning'),
              ( 102, 1, 1,  266,  430, 'attribute-icon-1020013', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-hvac.svg',                                            'Individually controlled HVAC units'),
              ( 103, 1, 1,  267,  431, 'attribute-icon-1020014', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-wheelchair.svg',                                      'Wheelchair Accessible Units'),
              ( 104, 1, 1,  268,  432, 'attribute-icon-1020015', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-restaurant.svg',                                      'Private Dining Room'),
              ( 105, 1, 1,  269,  433, 'attribute-icon-1020016', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-restaurant.svg',                                      'Bistro Area'),
              ( 106, 1, 1,  270,  434, 'attribute-icon-1020017', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-patio.svg',                                           'Patio Dining'),
              ( 107, 1, 1,  271,  435, 'attribute-icon-1020018', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-ice-cream.svg',                                       'Ice Cream Parlor'),
              ( 108, 1, 1,  272,  436, 'attribute-icon-1020019', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-kitchen.svg',                                         'Resident Kitchen'),
              ( 109, 1, 1,  273,  437, 'attribute-icon-1020020', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-hair-dryer.svg',                                      'Barber/Beauty Salon'),
              ( 110, 1, 1,  274,  438, 'attribute-icon-1020021', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-spa-lotus.svg',                                       'Spa Services'),
              ( 111, 1, 1,  275,  439, 'attribute-icon-1020022', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-spa-lotus.svg',                                       'Sauna'),
              ( 112, 1, 1,  276,  440, 'attribute-icon-1020023', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-fitness.svg',                                         'Gym'),
              ( 113, 1, 1,  277,  441, 'attribute-icon-1020024', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-fitness.svg',                                         'Fitness Equipment'),
              ( 114, 1, 1,  278,  442, 'attribute-icon-1020025', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-chapel.svg',                                          'Chapel'),
              ( 115, 1, 1,  279,  443, 'attribute-icon-1020026', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-camera.svg',                                          'Theater'),
              ( 116, 1, 1,  280,  444, 'attribute-icon-1020027', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-smart-tv.svg',                                        'Large Screen TV Lounge'),
              ( 117, 1, 1,  281,  445, 'attribute-icon-1020028', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-armchair.svg',                                        'Lounge Area'),
              ( 118, 1, 1,  282,  446, 'attribute-icon-1020029', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-ping-pong.svg',                                       'Activity Room'),
              ( 119, 1, 1,  283,  447, 'attribute-icon-1020030', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-ping-pong.svg',                                       'Game Room'),
              ( 120, 1, 1,  284,  448, 'attribute-icon-1020031', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-pool-table.svg',                                      'Billiard Lounge'),
              ( 121, 1, 1,  285,  449, 'attribute-icon-1020032', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-library.svg',                                         'Library'),
              ( 122, 1, 1,  286,  450, 'attribute-icon-1020033', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-music.svg',                                           'Music Room'),
              ( 123, 1, 1,  287,  451, 'attribute-icon-1020034', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-screen.svg',                                          'Computer Room with Internet Access'),
              ( 124, 1, 1,  288,  452, 'attribute-icon-1020035', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-shop.svg',                                            'Country Store'),
              ( 125, 1, 1,  289,  453, 'attribute-icon-1020036', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-shop.svg',                                            'Gift Shop'),
              ( 126, 1, 1,  290,  454, 'attribute-icon-1020037', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-rose.svg',                                            'Community Grounds'),
              ( 127, 1, 1,  291,  455, 'attribute-icon-1020038', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-plant.svg',                                           'Garden'),
              ( 128, 1, 1,  292,  456, 'attribute-icon-1020039', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-sunbed.svg',                                          'Patio Area'),
              ( 129, 1, 1,  293,  457, 'attribute-icon-1020040', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-landscape.svg',                                       'Walking Paths'),
              ( 130, 1, 1,  294,  458, 'attribute-icon-1020041', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-koi-pond.svg',                                        'Koi Pond'),
              ( 131, 1, 1,  295,  459, 'attribute-icon-1020042', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-swimming-pool.svg',                                   'Outdoor Swimming Pool'),
              ( 132, 1, 1,  296,  460, 'attribute-icon-1020043', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-swimming-pool.svg',                                   'Poolside Clubhouse'),
              ( 133, 1, 1,  297,  461, 'attribute-icon-1020044', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-swimming-pool.svg',                                   'Screened Heated Swimming Pool'),
              ( 134, 1, 1,  298,  462, 'attribute-icon-1020045', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-swimming-pool.svg',                                   'Swimming Pool'),
              ( 135, 1, 1,  299,  463, 'attribute-icon-1020046', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-sauna.svg',                                           'Jacuzzi'),
              ( 136, 1, 1,  300,  464, 'attribute-icon-1020047', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-car.svg',                                             'Parking'),
              ( 137, 1, 1,  301,  465, 'attribute-icon-1020048', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-car.svg',                                             'Covered Parking'),
              ( 138, 1, 1,  302,  466, 'attribute-icon-1020049', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-car.svg',                                             'Garage Parking'),
              ( 139, 1, 1,  303,  467, 'attribute-icon-1020050', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-car.svg',                                             'Gated Underground Parking'),
              ( 140, 1, 1,  304,  468, 'attribute-icon-1020051', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-car.svg',                                             'Heated Underground Parking'),
              ( 141, 1, 1,  305,  469, 'attribute-icon-1020052', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-wifi.svg',                                            'WiFi in Common Areas'),
              ( 142, 1, 1,  306,  470, 'attribute-icon-1020053', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-laundry.svg',                                         'Laundry Facilities'),
              ( 143, 1, 1,  307,  471, 'attribute-icon-1020054', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-laundry.svg',                                         'Washer and Dryer'),
              ( 144, 1, 1,  308,  472, 'attribute-icon-1020055', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-trash.svg',                                           'Trash Chutes'),
              ( 145, 1, 1,  309,  473, 'attribute-icon-1020056', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-fireplace.svg',                                       'Community Fireplace'),
              ( 146, 1, 1,  310,  474, 'attribute-icon-1020057', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-mailbox.svg',                                         'Locked Mailboxes'),
              ( 147, 1, 1,  311,  475, 'attribute-icon-1020058', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-safety-rails.svg',                                    'Safety Rails'),
              ( 148, 1, 1,  312,  476, 'attribute-icon-1020059', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-fire-extinguisher.svg',                               'Smoke Alarm and Sprinkler System'),
              ( 149, 1, 1,  313,  477, 'attribute-icon-1020060', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-pets.svg',                                            'Pets Welcome'),
              ( 150, 1, 1,  314,  478, 'attribute-icon-1020061', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-document.svg',                                        'Renters Liability Insurance Program'),
              ( 151, 1, 1,  315,  479, 'attribute-icon-1020062', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-wheelchair.svg',                                      'Wheelchair Accessible'),
              ( 152, 1, 1,  316,  480, 'attribute-icon-1020064', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-bedroom.svg',                                         'Cottages'),
              ( 153, 1, 1,  317,  481, 'attribute-icon-1020065', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-room-service.svg',                                    'Three Chef Prepared Meals Daily'),
              ( 154, 1, 1,  318,  482, 'attribute-icon-1020066', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-calendar.svg',                                        'Full Calendar of Enriching Activities'),
              ( 155, 1, 1,  319,  483, 'attribute-icon-1020067', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-bus.svg',                                             'Complimentary Scheduled Transportation'),
              ( 156, 1, 1,  320,  484, 'attribute-icon-1020068', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-cleaning-spray.svg',                                  'Weekly Housekeeping'),
              ( 157, 1, 1,  321,  485, 'attribute-icon-1020069', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-laundry-iron.svg',                                    'Light Linen Service'),
              ( 158, 1, 1,  322,  486, 'attribute-icon-1020070', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-mouse.svg',                                           'Lively Mobile Plus Personal Emergency Response Device'),
              ( 159, 1, 1,  323,  487, 'attribute-icon-1020071', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-wrench.svg',                                          'Maintenance'),
              ( 160, 1, 1,  324,  488, 'attribute-icon-1020072', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-bulb.svg',                                            'Most Utilities Included'),
              ( 161, 1, 1,  325,  489, 'attribute-icon-1020073', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-travel.svg',                                          'Exclusive Travel and Stay Program'),
              ( 162, 1, 1,  326,  490, 'attribute-icon-1020074', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-mouse.svg',                                           'Personal Emergency Response Device'),
              ( 163, 1, 1,  327,  491, 'attribute-icon-1020075', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-oven.svg',                                            'Full Kitchen or Kitchenette'),
              ( 164, 1, 1,  328,  492, 'attribute-icon-1020063', NULL,   'https://staswuse.blob.core.windows.net/northstar/comunity-attributes/hol-bedroom.svg',                                         'Guest Suite'),

              -- Northstar Moon Over Nowhere
              ( 265, 1, 1,  561,  561, NULL,                     NULL,   'https://staswuse.blob.core.windows.net/northstar/communities/30100.jpg',                                                       '30100.jpg'),
              ( 165, 1, 1, NULL, NULL, '20403',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30100/images/atria-campana-del-rio-01_16x9.jpg',                  'northstar-moon-over-nowhere-01_16x9.jpg'),
              ( 166, 1, 1, NULL, NULL, '20404',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30100/images/atria-campana-del-rio-01_4x3.jpg',                   'northstar-moon-over-nowhere-01_4x3.jpg'),
              ( 167, 1, 1, NULL,  493, '20405',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30100/images/atria-campana-del-rio-02_16x9.jpg',                  'northstar-moon-over-nowhere-02_16x9.jpg'),
              ( 168, 1, 1, NULL,  494, '20406',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30100/images/atria-campana-del-rio-02_4x3.jpg',                   'northstar-moon-over-nowhere-02_4x3.jpg'),
              ( 169, 1, 1, NULL,  495, '20407',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30100/images/atria-campana-del-rio-03_16x9.jpg',                  'northstar-moon-over-nowhere-03_16x9.jpg'),
              ( 170, 1, 1, NULL,  496, '20408',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30100/images/atria-campana-del-rio-03_4x3.jpg',                   'northstar-moon-over-nowhere-03_4x3.jpg'),
              ( 171, 1, 1, NULL,  497, '20409',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30100/images/atria-campana-del-rio-04_16x9.jpg',                  'northstar-moon-over-nowhere-04_16x9.jpg'),
              ( 172, 1, 1, NULL,  498, '20410',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30100/images/atria-campana-del-rio-04_4x3.jpg',                   'northstar-moon-over-nowhere-04_4x3.jpg'),
              ( 173, 1, 1, NULL,  499, '20411',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30100/images/atria-campana-del-rio-05_16x9.jpg',                  'northstar-moon-over-nowhere-05_16x9.jpg'),
              ( 174, 1, 1, NULL,  500, '20412',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30100/images/atria-campana-del-rio-05_4x3.jpg',                   'northstar-moon-over-nowhere-05_4x3.jpg'),
              ( 175, 1, 1, NULL,  501, '20413',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30100/images/atria-campana-del-rio-06_16x9.jpg',                  'northstar-moon-over-nowhere-06_16x9.jpg'),
              ( 176, 1, 1, NULL,  502, '20414',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30100/images/atria-campana-del-rio-06_4x3.jpg',                   'northstar-moon-over-nowhere-06_4x3.jpg'),

              ( 289, 1, 2, NULL, NULL, '10270-alil-one-bedroom', NULL,   'https://staswuse.blob.core.windows.net/northstar/communities/30100/floor-plans/10270-alil-one-bedroom',                        '10270-alil-one-bedroom'),
              ( 290, 1, 2, NULL, NULL, '10270-alil-studio',      NULL,   'https://staswuse.blob.core.windows.net/northstar/communities/30100/floor-plans/10270-alil-studio',                             '10270-alil-studio'),
              ( 291, 1, 2, NULL, NULL, '10270-alil-two-bedroom', NULL,   'https://staswuse.blob.core.windows.net/northstar/communities/30100/floor-plans/10270-alil-two-bedroom',                        '10270-alil-two-bedroom'),
              ( 292, 1, 2, NULL, NULL, '10270-il-one-bedroom',   NULL,   'https://staswuse.blob.core.windows.net/northstar/communities/30100/floor-plans/10270-il-one-bedroom',                          '10270-il-one-bedroom'),
              ( 293, 1, 2, NULL, NULL, '10270-il-studio',        NULL,   'https://staswuse.blob.core.windows.net/northstar/communities/30100/floor-plans/10270-il-studio',                               '10270-il-studio'),
              ( 294, 1, 2, NULL, NULL, '10270-il-two-bedroom',   NULL,   'https://staswuse.blob.core.windows.net/northstar/communities/30100/floor-plans/10270-il-two-bedroom',                          '10270-il-two-bedroom'),
              ( 271, 1, 2, NULL, NULL, '10270-il-villa',         NULL,   'https://staswuse.blob.core.windows.net/northstar/communities/30100/floor-plans/10270-il-villa',                                '10270-il-villa'),
              ( 272, 1, 2, NULL, NULL, '10270-mc-shared-suite',  NULL,   'https://staswuse.blob.core.windows.net/northstar/communities/30100/floor-plans/10270-mc-shared-suite',                         '10270-mc-shared-suite'),
              ( 273, 1, 2, NULL, NULL, '10270-mc-studio',        NULL,   'https://staswuse.blob.core.windows.net/northstar/communities/30100/floor-plans/10270-mc-studio',                               '10270-mc-studio'),

              -- Northstar Homeowners Realty
              ( 266, 1, 1,  562,  562, NULL,                     NULL,   'https://staswuse.blob.core.windows.net/northstar/communities/30101.jpg',                                                       '30101.jpg'),
              ( 177, 1, 1, NULL, NULL, '21109',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30101/images/apartment-04_16x9.jpg',                              'apartment-04_16x9.jpg'),
              ( 178, 1, 1, NULL, NULL, '21110',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30101/images/apartment-04_4x3.jpg',                               'apartment-04_4x3.jpg'),
              ( 179, 1, 1, NULL,  503, '21111',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30101/images/atria-bell-court-gardens-01_16x9.jpg',               'atria-bell-court-gardens-01_16x9.jpg'),
              ( 180, 1, 1, NULL,  504, '21112',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30101/images/atria-bell-court-gardens-01_4x3.jpg',                'atria-bell-court-gardens-01_4x3.jpg'),
              ( 181, 1, 1, NULL,  505, '21113',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30101/images/atria-bell-court-gardens-02_16x9.jpg',               'atria-bell-court-gardens-02_16x9.jpg'),
              ( 182, 1, 1, NULL,  506, '21114',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30101/images/atria-bell-court-gardens-02_4x3.jpg',                'atria-bell-court-gardens-02_4x3.jpg'),
              ( 183, 1, 1, NULL,  507, '21115',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30101/images/atria-bell-court-gardens-03_16x9.jpg',               'atria-bell-court-gardens-03_16x9.jpg'),
              ( 184, 1, 1, NULL,  508, '21116',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30101/images/atria-bell-court-gardens-03_4x3.jpg',                'atria-bell-court-gardens-03_4x3.jpg'),
              ( 185, 1, 1, NULL,  509, '21117',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30101/images/atria-bell-court-gardens-04_16x9.jpg',               'atria-bell-court-gardens-04_16x9.jpg'),
              ( 186, 1, 1, NULL,  510, '21118',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30101/images/atria-bell-court-gardens-04_4x3.jpg',                'atria-bell-court-gardens-04_4x3.jpg'),
              ( 187, 1, 1, NULL,  511, '21119',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30101/images/atria-bell-court-gardens-05_16x9.jpg',               'atria-bell-court-gardens-05_16x9.jpg'),
              ( 188, 1, 1, NULL,  512, '21120',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30101/images/atria-bell-court-gardens-05_4x3.jpg',                'atria-bell-court-gardens-05_4x3.jpg'),
              ( 189, 1, 1, NULL,  513, '21121',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30101/images/atria-bell-court-gardens-06_16x9.jpg',               'atria-bell-court-gardens-06_16x9.jpg'),
              ( 190, 1, 1, NULL,  514, '21122',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30101/images/atria-bell-court-gardens-06_4x3.jpg',                'atria-bell-court-gardens-06_4x3.jpg'),
              ( 191, 1, 1, NULL,  515, '21123',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30101/images/atria-bell-court-gardens-07_16x9.jpg',               'atria-bell-court-gardens-07_16x9.jpg'),
              ( 192, 1, 1, NULL,  516, '21124',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30101/images/atria-bell-court-gardens-07_4x3.jpg',                'atria-bell-court-gardens-07_4x3.jpg'),
              ( 193, 1, 1, NULL,  517, '21125',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30101/images/atria-bell-court-gardens-08_16x9.jpg',               'atria-bell-court-gardens-08_16x9.jpg'),
              ( 194, 1, 1, NULL,  518, '21126',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30101/images/atria-bell-court-gardens-08_4x3.jpg',                'atria-bell-court-gardens-08_4x3.jpg'),
              ( 195, 1, 1, NULL,  519, '21127',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30101/images/atria-bell-court-gardens-09_16x9.jpg',               'atria-bell-court-gardens-09_16x9.jpg'),
              ( 196, 1, 1, NULL,  520, '21128',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30101/images/atria-bell-court-gardens-09_4x3.jpg',                'atria-bell-court-gardens-09_4x3.jpg'),

              ( 274, 1, 2, NULL, NULL, '10342-il-one-bedroom',   NULL,   'https://staswuse.blob.core.windows.net/northstar/communities/30101/floor-plans/10342-il-one-bedroom.pdf',                      '10342-il-one-bedroom'),
              ( 275, 1, 2, NULL, NULL, '10342-il-two-bedroom',   NULL,   'https://staswuse.blob.core.windows.net/northstar/communities/30101/floor-plans/10342-il-two-bedroom.pdf',                      '10342-il-two-bedroom'),

              -- Northstar La Casa Grande
              ( 267, 1, 1,  563,  563, NULL,                     NULL,   'https://staswuse.blob.core.windows.net/northstar/communities/30102.jpg',                                                       '30102.jpg'),
              ( 197, 1, 1, NULL, NULL, '20415',                  '16x9', 'https://stdcmsproduse.blob.core.windows.net/51608b38-07fc-4171-a6de-f3605787cf24/images/10272/atria-valley-manor-01_16x9.jpg', 'atria-valley-manor-01_16x9.jpg'),
              ( 198, 1, 1, NULL, NULL, '20416',                  '4x3',  'https://stdcmsproduse.blob.core.windows.net/51608b38-07fc-4171-a6de-f3605787cf24/images/10272/atria-valley-manor-01_4x3.jpg',  'atria-valley-manor-01_4x3.jpg'),
              ( 199, 1, 1, NULL, NULL, '20417',                  '16x9', 'https://stdcmsproduse.blob.core.windows.net/51608b38-07fc-4171-a6de-f3605787cf24/images/10272/atria-valley-manor-02_16x9.jpg', 'atria-valley-manor-02_16x9.jpg'),
              ( 200, 1, 1, NULL, NULL, '20418',                  '4x3',  'https://stdcmsproduse.blob.core.windows.net/51608b38-07fc-4171-a6de-f3605787cf24/images/10272/atria-valley-manor-02_4x3.jpg',  'atria-valley-manor-02_4x3.jpg'),
              ( 201, 1, 1, NULL, NULL, '20419',                  '16x9', 'https://stdcmsproduse.blob.core.windows.net/51608b38-07fc-4171-a6de-f3605787cf24/images/10272/atria-valley-manor-03_16x9.jpg', 'atria-valley-manor-03_16x9.jpg'),
              ( 202, 1, 1, NULL, NULL, '20420',                  '4x3',  'https://stdcmsproduse.blob.core.windows.net/51608b38-07fc-4171-a6de-f3605787cf24/images/10272/atria-valley-manor-03_4x3.jpg',  'atria-valley-manor-03_4x3.jpg'),
              ( 203, 1, 1, NULL, NULL, '20421',                  '16x9', 'https://stdcmsproduse.blob.core.windows.net/51608b38-07fc-4171-a6de-f3605787cf24/images/10272/atria-valley-manor-04_16x9.jpg', 'atria-valley-manor-04_16x9.jpg'),
              ( 204, 1, 1, NULL, NULL, '20422',                  '4x3',  'https://stdcmsproduse.blob.core.windows.net/51608b38-07fc-4171-a6de-f3605787cf24/images/10272/atria-valley-manor-04_4x3.jpg',  'atria-valley-manor-04_4x3.jpg'),
              ( 205, 1, 1, NULL, NULL, '20423',                  '16x9', 'https://stdcmsproduse.blob.core.windows.net/51608b38-07fc-4171-a6de-f3605787cf24/images/10272/atria-valley-manor-05_16x9.jpg', 'atria-valley-manor-05_16x9.jpg'),
              ( 206, 1, 1, NULL, NULL, '20424',                  '4x3',  'https://stdcmsproduse.blob.core.windows.net/51608b38-07fc-4171-a6de-f3605787cf24/images/10272/atria-valley-manor-05_4x3.jpg',  'atria-valley-manor-05_4x3.jpg'),

              ( 276, 1, 2, NULL, NULL, '10272-il-studio',        NULL,   'https://staswuse.blob.core.windows.net/northstar/communities/30102/floor-plans/10272-il-studio.pdf',                           '10272-il-studio'),
              ( 277, 1, 2, NULL, NULL, '10272-il-one-bedroom',   NULL,   'https://staswuse.blob.core.windows.net/northstar/communities/30102/floor-plans/10272-il-one-bedroom.pdf',                      '10272-il-one-bedroom'),
              ( 278, 1, 2, NULL, NULL, '10272-il-two-bedroom',   NULL,   'https://staswuse.blob.core.windows.net/northstar/communities/30102/floor-plans/10272-il-two-bedroom.pdf',                      '10272-il-two-bedroom'),


              -- Northstar Tower of Hope
              ( 268, 1, 1,  564,  564, NULL,                     NULL,   'https://staswuse.blob.core.windows.net/northstar/communities/30105.jpg',                                                       '30105.jpg'),
              ( 207, 1, 1, NULL,  521, '20425',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30105/images/atria-hearthstone-east-01_16x9.jpg',                 'atria-hearthstone-east-01_16x9.jpg'),
              ( 208, 1, 1, NULL,  522, '20426',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30105/images/atria-hearthstone-east-01_4x3.jpg',                  'atria-hearthstone-east-01_4x3.jpg'),
              ( 209, 1, 1, NULL,  523, '20427',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30105/images/atria-hearthstone-east-02_16x9.jpg',                 'atria-hearthstone-east-02_16x9.jpg'),
              ( 210, 1, 1, NULL,  524, '20428',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30105/images/atria-hearthstone-east-02_4x3.jpg',                  'atria-hearthstone-east-02_4x3.jpg'),
              ( 211, 1, 1, NULL,  525, '20429',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30105/images/atria-hearthstone-east-03_16x9.jpg',                 'atria-hearthstone-east-03_16x9.jpg'),
              ( 212, 1, 1, NULL,  526, '20430',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30105/images/atria-hearthstone-east-03_4x3.jpg',                  'atria-hearthstone-east-03_4x3.jpg'),
              ( 213, 1, 1, NULL,  527, '20431',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30105/images/atria-hearthstone-east-04_16x9.jpg',                 'atria-hearthstone-east-04_16x9.jpg'),
              ( 214, 1, 1, NULL,  528, '20432',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30105/images/atria-hearthstone-east-04_4x3.jpg',                  'atria-hearthstone-east-04_4x3.jpg'),
              ( 215, 1, 1, NULL,  529, '20433',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30105/images/atria-hearthstone-east-05_16x9.jpg',                 'atria-hearthstone-east-05_16x9.jpg'),
              ( 216, 1, 1, NULL,  530, '20434',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30105/images/atria-hearthstone-east-05_4x3.jpg',                  'atria-hearthstone-east-05_4x3.jpg'),
              ( 217, 1, 1, NULL,  531, '20435',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30105/images/atria-hearthstone-east-06_16x9.jpg',                 'atria-hearthstone-east-06_16x9.jpg'),
              ( 218, 1, 1, NULL,  532, '20436',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30105/images/atria-hearthstone-east-06_4x3.jpg',                  'atria-hearthstone-east-06_4x3.jpg'),
              ( 219, 1, 1, NULL,  533, '20437',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30105/images/atria-hearthstone-east-07_16x9.jpg',                 'atria-hearthstone-east-07_16x9.jpg'),
              ( 220, 1, 1, NULL,  534, '20438',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30105/images/atria-hearthstone-east-07_4x3.jpg',                  'atria-hearthstone-east-07_4x3.jpg'),
              ( 221, 1, 1, NULL,  535, '20439',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30105/images/atria-hearthstone-east-08_16x9.jpg',                 'atria-hearthstone-east-08_16x9.jpg'),
              ( 222, 1, 1, NULL,  536, '20440',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30105/images/atria-hearthstone-east-08_4x3.jpg',                  'atria-hearthstone-east-08_4x3.jpg'),
              ( 223, 1, 1, NULL,  537, '20441',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30105/images/atria-hearthstone-east-09_16x9.jpg',                 'atria-hearthstone-east-09_16x9.jpg'),
              ( 224, 1, 1, NULL,  538, '20442',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30105/images/atria-hearthstone-east-09_4x3.jpg',                  'atria-hearthstone-east-09_4x3.jpg'),
              ( 225, 1, 1, NULL, NULL, '20443',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30105/images/atria-hearthstone-west-01_16x9.jpg',                 'atria-hearthstone-west-01_16x9.jpg'),
              ( 226, 1, 1, NULL, NULL, '20444',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30105/images/atria-hearthstone-west-01_4x3.jpg',                  'atria-hearthstone-west-01_4x3.jpg'),
              ( 227, 1, 1, NULL, NULL, '20445',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30105/images/atria-hearthstone-west-02_16x9.jpg',                 'atria-hearthstone-west-02_16x9.jpg'),
              ( 228, 1, 1, NULL, NULL, '20446',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30105/images/atria-hearthstone-west-02_4x3.jpg',                  'atria-hearthstone-west-02_4x3.jpg'),
              ( 229, 1, 1, NULL, NULL, '20447',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30105/images/atria-hearthstone-west-03_16x9.jpg',                 'atria-hearthstone-west-03_16x9.jpg'),
              ( 230, 1, 1, NULL, NULL, '20448',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30105/images/atria-hearthstone-west-03_4x3.jpg',                  'atria-hearthstone-west-03_4x3.jpg'),
              ( 231, 1, 1, NULL, NULL, '20449',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30105/images/atria-hearthstone-west-04_16x9.jpg',                 'atria-hearthstone-west-04_16x9.jpg'),
              ( 232, 1, 1, NULL, NULL, '20450',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30105/images/atria-hearthstone-west-04_4x3.jpg',                  'atria-hearthstone-west-04_4x3.jpg'),
              ( 233, 1, 1, NULL, NULL, '20451',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30105/images/atria-hearthstone-west-05_16x9.jpg',                 'atria-hearthstone-west-05_16x9.jpg'),
              ( 234, 1, 1, NULL, NULL, '20452',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30105/images/atria-hearthstone-west-05_4x3.jpg',                  'atria-hearthstone-west-05_4x3.jpg'),
              ( 235, 1, 1, NULL, NULL, '20455',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30105/images/atria-hearthstone-west-07_16x9.jpg',                 'atria-hearthstone-west-07_16x9.jpg'),
              ( 236, 1, 1, NULL, NULL, '20456',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30105/images/atria-hearthstone-west-07_4x3.jpg',                  'atria-hearthstone-west-07_4x3.jpg'),

              ( 279, 1, 2, NULL, NULL, '10277-al-one-bedroom',   NULL,   'https://staswuse.blob.core.windows.net/northstar/communities/30105/floor-plans/10277-al-one-bedroom.pdf',                      '10277-al-one-bedroom'),
              ( 280, 1, 2, NULL, NULL, '10277-al-studio',        NULL,   'https://staswuse.blob.core.windows.net/northstar/communities/30105/floor-plans/10277-al-studio.pdf',                           '10277-al-studio'),
              ( 281, 1, 2, NULL, NULL, '10277-al-studio-deluxe', NULL,   'https://staswuse.blob.core.windows.net/northstar/communities/30105/floor-plans/10277-al-studio-deluxe.pdf',                    '10277-al-studio-deluxe'),
              ( 282, 1, 2, NULL, NULL, '10277-il-one-bedroom',   NULL,   'https://staswuse.blob.core.windows.net/northstar/communities/30105/floor-plans/10277-il-one-bedroom.pdf',                      '10277-il-one-bedroom'),
              ( 283, 1, 2, NULL, NULL, '10277-il-studio',        NULL,   'https://staswuse.blob.core.windows.net/northstar/communities/30105/floor-plans/10277-il-studio.pdf',                           '10277-il-studio'),
              ( 284, 1, 2, NULL, NULL, '10277-il-two-bedroom',   NULL,   'https://staswuse.blob.core.windows.net/northstar/communities/30105/floor-plans/10277-il-two-bedroom.pdf',                      '10277-il-two-bedroom'),


              -- Northstar Exuberanch
              ( 269, 1, 1,  565,  565, NULL,                     NULL,   'https://staswuse.blob.core.windows.net/northstar/communities/30106.jpg',                                                       '30106.jpg'),
              ( 237, 1, 1, NULL, NULL, '20025',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30106/atria-weston-place-01_16x9.jpg',                            'atria-weston-place-01_16x9.jpg'),
              ( 238, 1, 1, NULL, NULL, '20026',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30106/atria-weston-place-01_4x3.jpg',                             'atria-weston-place-01_4x3.jpg'),
              ( 239, 1, 1, NULL, NULL, '20027',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30106/atria-weston-place-02_16x9.jpg',                            'atria-weston-place-02_16x9.jpg'),
              ( 240, 1, 1, NULL, NULL, '20028',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30106/atria-weston-place-02_4x3.jpg',                             'atria-weston-place-02_4x3.jpg'),
              ( 241, 1, 1, NULL, NULL, '20029',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30106/atria-weston-place-03_16x9.jpg',                            'atria-weston-place-03_16x9.jpg'),
              ( 242, 1, 1, NULL, NULL, '20030',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30106/atria-weston-place-03_4x3.jpg',                             'atria-weston-place-03_4x3.jpg'),
              ( 243, 1, 1, NULL, NULL, '20031',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30106/atria-weston-place-04_16x9.jpg',                            'atria-weston-place-04_16x9.jpg'),
              ( 244, 1, 1, NULL, NULL, '20032',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30106/atria-weston-place-04_4x3.jpg',                             'atria-weston-place-04_4x3.jpg'),
              ( 245, 1, 1, NULL, NULL, '20033',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30106/atria-weston-place-05_16x9.jpg',                            'atria-weston-place-05_16x9.jpg'),
              ( 246, 1, 1, NULL, NULL, '20034',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30106/atria-weston-place-05_4x3.jpg',                             'atria-weston-place-05_4x3.jpg'),
              ( 247, 1, 1, NULL, NULL, '20035',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30106/atria-weston-place-06_16x9.jpg',                            'atria-weston-place-06_16x9.jpg'),
              ( 248, 1, 1, NULL, NULL, '20036',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30106/atria-weston-place-06_4x3.jpg',                             'atria-weston-place-06_4x3.jpg'),

              ( 285, 1, 2, NULL, NULL, '10205-alil-one-bedroom',   NULL,   'https://staswuse.blob.core.windows.net/northstar/communities/30106/floor-plans/10205-alil-one-bedroom.pdf',                  '10205-alil-one-bedroom'),
              ( 286, 1, 2, NULL, NULL, '10205-alil-studio',        NULL,   'https://staswuse.blob.core.windows.net/northstar/communities/30106/floor-plans/10205-alil-studio.pdf',                       '10205-alil-studio'),
              ( 287, 1, 2, NULL, NULL, '10205-mc-shared-suite',    NULL,   'https://staswuse.blob.core.windows.net/northstar/communities/30106/floor-plans/10205-mc-shared-suite.pdf',                   '10205-mc-shared-suite'),
              ( 288, 1, 2, NULL, NULL, '10205-mc-studio',          NULL,   'https://staswuse.blob.core.windows.net/northstar/communities/30106/floor-plans/10205-mc-studio.pdf',                         '10205-mc-studio.pdf'),

              -- Northstar Stone Ranch
              ( 270, 1, 1,  566,  566, NULL,                     NULL,   'https://staswuse.blob.core.windows.net/northstar/communities/30108.jpg',                                                       '30108.jpg'),
              ( 249, 1, 1, NULL,  539, '20037',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30108/images/atria-cypresswood-01_16x9.jpg',                      'atria-cypresswood-01_16x9.jpg'),
              ( 250, 1, 1, NULL,  540, '20038',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30108/images/atria-cypresswood-01_4x3.jpg',                       'atria-cypresswood-01_4x3.jpg'),
              ( 251, 1, 1, NULL,  541, '20039',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30108/images/atria-cypresswood-02_16x9.jpg',                      'atria-cypresswood-02_16x9.jpg'),
              ( 252, 1, 1, NULL,  542, '20040',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30108/images/atria-cypresswood-02_4x3.jpg',                       'atria-cypresswood-02_4x3.jpg'),
              ( 253, 1, 1, NULL,  543, '20041',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30108/images/atria-cypresswood-03_16x9.jpg',                      'atria-cypresswood-03_16x9.jpg'),
              ( 254, 1, 1, NULL,  544, '20042',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30108/images/atria-cypresswood-03_4x3.jpg',                       'atria-cypresswood-03_4x3.jpg'),
              ( 255, 1, 1, NULL,  545, '20043',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30108/images/atria-cypresswood-04_16x9.jpg',                      'atria-cypresswood-04_16x9.jpg'),
              ( 256, 1, 1, NULL,  546, '20044',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30108/images/atria-cypresswood-04_4x3.jpg',                       'atria-cypresswood-04_4x3.jpg'),
              ( 257, 1, 1, NULL,  547, '20045',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30108/images/atria-cypresswood-05_16x9.jpg',                      'atria-cypresswood-05_16x9.jpg'),
              ( 258, 1, 1, NULL,  548, '20046',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30108/images/atria-cypresswood-05_4x3.jpg',                       'atria-cypresswood-05_4x3.jpg'),
              ( 259, 1, 1, NULL,  549, '20047',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30108/images/atria-cypresswood-06_16x9.jpg',                      'atria-cypresswood-06_16x9.jpg'),
              ( 260, 1, 1, NULL,  550, '20048',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30108/images/atria-cypresswood-06_4x3.jpg',                       'atria-cypresswood-06_4x3.jpg'),
              ( 261, 1, 1, NULL,  551, '20049',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30108/images/atria-cypresswood-07_16x9.jpg',                      'atria-cypresswood-07_16x9.jpg'),
              ( 262, 1, 1, NULL,  552, '20050',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30108/images/atria-cypresswood-07_4x3.jpg',                       'atria-cypresswood-07_4x3.jpg'),
              ( 263, 1, 1, NULL,  553, '20051',                  '16x9', 'https://staswuse.blob.core.windows.net/northstar/communities/30108/images/atria-cypresswood-08_16x9.jpg',                      'atria-cypresswood-08_16x9.jpg'),
              ( 264, 1, 1, NULL,  554, '20052',                  '4x3',  'https://staswuse.blob.core.windows.net/northstar/communities/30108/images/atria-cypresswood-08_4x3.jpg',                       'atria-cypresswood-08_4x3.jpg'))
AS SOURCE (DigitalAssetId,
           IsActive,
           DigitalAssetTypeId,
           AltTextId,
           CaptionId,
           ExternalId,
           Discriminator,
           DigitalAssetUrl,
           DigitalAssetName)
ON TARGET.DigitalAssetId = SOURCE.DigitalAssetId
WHEN MATCHED THEN UPDATE SET TARGET.ExternalId         = SOURCE.ExternalId,
                             TARGET.Discriminator      = SOURCE.Discriminator,
                             TARGET.DigitalAssetTypeId = SOURCE.DigitalAssetTypeId,
                             TARGET.DigitalAssetUrl    = SOURCE.DigitalAssetUrl,
                             TARGET.DigitalAssetName   = SOURCE.DigitalAssetName,
                             TARGET.AltTextId          = SOURCE.AltTextId,
                             TARGET.CaptionId          = SOURCE.CaptionId
WHEN NOT MATCHED THEN INSERT (DigitalAssetId,
                              ExternalId,
                              Discriminator,
                              DigitalAssetTypeId,
                              DigitalAssetUrl,
                              DigitalAssetName,
                              AltTextId,
                              CaptionId)
                      VALUES (SOURCE.DigitalAssetId,
                              SOURCE.ExternalId,
                              SOURCE.Discriminator,
                              SOURCE.DigitalAssetTypeId,
                              SOURCE.DigitalAssetUrl,
                              SOURCE.DigitalAssetName,
                              SOURCE.AltTextId,
                              SOURCE.CaptionId);

SET IDENTITY_INSERT PM.DigitalAsset OFF
GO