MERGE PM.ContentCopy AS TARGET
USING (VALUES 
              (   1, 'en-US', 'Restaurant with Table Service'),
              (   2, 'en-US', 'Bistro'),
              (   3, 'en-US', 'Grille'),
              (   4, 'en-US', 'Cocktail Lounge'),
              (   5, 'en-US', 'Pub'),
              (   6, 'en-US', 'Private Dining Room'),
              (   7, 'en-US', 'Sports Lounge'),
              (   8, 'en-US', 'Hot Tub'),
              (   9, 'en-US', 'Indoor Swimming Pool'),
              (  10, 'en-US', 'Outdoor Swimming Pool'),
              (  11, 'en-US', 'Off-Site Pool Privileges'),
              (  12, 'en-US', 'Covered Parking'),
              (  13, 'en-US', 'Parking Garage'),
              (  14, 'en-US', 'Parking'),
              (  15, 'en-US', 'Courtyard'),
              (  16, 'en-US', 'Outdoor Dining Space'),
              (  17, 'en-US', 'Outdoor Fireplace'),
              (  18, 'en-US', 'Outdoor Grill'),
              (  19, 'en-US', 'Walking Path'),
              (  20, 'en-US', 'Patio'),
              (  21, 'en-US', 'Putting Green'),
              (  22, 'en-US', 'Resident Garden'),
              (  23, 'en-US', 'Cognitive Learning Center'),
              (  24, 'en-US', 'Library'),
              (  25, 'en-US', 'Media Room'),
              (  26, 'en-US', 'Movie Theater'),
              (  27, 'en-US', 'Fitness Center'),
              (  28, 'en-US', 'Physical Therapy Center'),
              (  29, 'en-US', 'Salon'),
              (  30, 'en-US', 'Salon & Spa'),
              (  31, 'en-US', 'On-Site Physician Office Space'),
              (  32, 'en-US', 'On-Site Sundries Shop'),
              (  33, 'en-US', 'Game Room'),
              (  34, 'en-US', 'Computers'),
              (  35, 'en-US', 'Wi-Fi in Common Areas'),
              (  36, 'en-US', 'Wi-Fi in Apartments'),
              (  37, 'en-US', 'Storage Units Available'),
              (  38, 'en-US', 'Pet-Friendly Environment'),
              (  39, 'en-US', '24-Hour Staff'),
              (  40, 'en-US', 'Alzheimer''s and Dementia Support Group'),
              (  41, 'en-US', 'Concierge Service'),
              (  42, 'en-US', 'Emergency Alert System'),
              (  43, 'en-US', 'Daily Educational, Social, Cultural, and Fitness Opportunities'),
              (  44, 'en-US', 'Locally-Inspired Cuisine'),
              (  45, 'en-US', 'Gluten-Free Meals'),
              (  46, 'en-US', 'Vegetarian Options'),
              (  47, 'en-US', 'Kosher Meals'),
              (  48, 'en-US', 'Low-Sodium Meals'),
              (  49, 'en-US', '3 Chef-Prepared Meals Per Day'),
              (  50, 'en-US', '3 Chef-Prepared Meals Per Day - Assisted Living'),
              (  51, 'en-US', '2 Chef-Prepared Meals Per Day - Assisted Living'),
              (  52, 'en-US', '2 Chef-Prepared Meals Per Day - Independent Living'),
              (  53, 'en-US', '1 Chef-Prepared Meal Per Day - Independent Living'),
              (  54, 'en-US', 'Housekeeping and Linen Service'),
              (  55, 'en-US', 'Community Laundry Service'),
              (  56, 'en-US', 'Fitness Trainer'),
              (  57, 'en-US', 'Massage Therapy'),
              (  58, 'en-US', 'Newspaper Delivery'),
              (  59, 'en-US', 'Scheduled Bus and Sedan Transportation'),
              (  60, 'en-US', 'Scheduled Sedan Transportation'),
              (  61, 'en-US', 'Scheduled Bus Transportation'),
              (  62, 'en-US', 'Scheduled Van Transportation'),
              (  63, 'en-US', 'Scheduled Sedan and Van Transportation'),
              (  64, 'en-US', 'Scheduled Bus and Van Transportation'),
              (  65, 'en-US', 'Scheduled Bus, Van, and Sedan Transportation'),
              (  66, 'en-US', 'Volunteer Programs'),
              (  67, 'en-US', 'On-Site Physical Therapy / Occupational Therapy'),
              (  68, 'en-US', 'On-Site Worship Services'),
              (  69, 'en-US', 'Electronic Key Entry'),
              (  70, 'en-US', 'Individual Thermostat Control'),
              (  71, 'en-US', 'Furnished Apartments Available'),
              (  72, 'en-US', 'Fully-Equipped Kitchen'),
              (  73, 'en-US', 'Kitchen or Kitchenette'),
              (  74, 'en-US', 'Kitchenette'),
              (  75, 'en-US', 'Microwave'),
              (  76, 'en-US', 'Refrigerator'),
              (  77, 'en-US', 'Balcony or Patio - Select Apartments'),
              (  78, 'en-US', 'Walk-In Closet'),
              (  79, 'en-US', 'Walk-In Shower'),
              (  80, 'en-US', 'Washer and Dryer - Select Apartments'),
              (  81, 'en-US', 'Washer and Dryer Hookups - Select Apartments'),
              (  82, 'en-US', 'Washer and Dryer'),
              (  83, 'en-US', 'Washer and Dryer - Independent Living'),
              (  84, 'en-US', 'Cable TV'),
              (  85, 'en-US', 'Utilities Included'),
              (  86, 'en-US', 'Apartment Maintenance'),
              (  87, 'en-US', 'Housekeeping and Linen Service'),
              (  88, 'en-US', 'Personal Laundry Service'),
              (  89, 'en-US', 'Full Kitchen in Units'),
              (  90, 'en-US', 'Kitchenette in Units'),
              (  91, 'en-US', 'Refrigerator'),
              (  92, 'en-US', 'Patio or Balcony'),
              (  93, 'en-US', 'Washer and Dryer'),
              (  94, 'en-US', 'Washer and Dryer Hookups'),
              (  95, 'en-US', 'Walk-in Closet'),
              (  96, 'en-US', 'Walk-in Tub'),
              (  97, 'en-US', 'WiFi in Apartments'),
              (  98, 'en-US', 'Basic Cable TV'),
              (  99, 'en-US', 'Telephone Hookups'),
              ( 100, 'en-US', 'Carpet and Window Treatments'),
              ( 101, 'en-US', 'Individually Controlled Heating and Air Conditioning'),
              ( 102, 'en-US', 'Individually controlled HVAC units'),
              ( 103, 'en-US', 'Wheelchair Accessible Units'),
              ( 104, 'en-US', 'Private Dining Room'),
              ( 105, 'en-US', 'Bistro Area'),
              ( 106, 'en-US', 'Patio Dining'),
              ( 107, 'en-US', 'Ice Cream Parlor'),
              ( 108, 'en-US', 'Resident Kitchen'),
              ( 109, 'en-US', 'Barber/Beauty Salon'),
              ( 110, 'en-US', 'Spa Services'),
              ( 111, 'en-US', 'Sauna'),
              ( 112, 'en-US', 'Gym'),
              ( 113, 'en-US', 'Fitness Equipment'),
              ( 114, 'en-US', 'Chapel'),
              ( 115, 'en-US', 'Theater'),
              ( 116, 'en-US', 'Large Screen TV Lounge'),
              ( 117, 'en-US', 'Lounge Area'),
              ( 118, 'en-US', 'Activity Room'),
              ( 119, 'en-US', 'Game Room'),
              ( 120, 'en-US', 'Billiard Lounge'),
              ( 121, 'en-US', 'Library'),
              ( 122, 'en-US', 'Music Room'),
              ( 123, 'en-US', 'Computer Room with Internet Access'),
              ( 124, 'en-US', 'Country Store'),
              ( 125, 'en-US', 'Gift Shop'),
              ( 126, 'en-US', 'Community Grounds'),
              ( 127, 'en-US', 'Garden'),
              ( 128, 'en-US', 'Patio Area'),
              ( 129, 'en-US', 'Walking Paths'),
              ( 130, 'en-US', 'Koi Pond'),
              ( 131, 'en-US', 'Outdoor Swimming Pool'),
              ( 132, 'en-US', 'Poolside Clubhouse'),
              ( 133, 'en-US', 'Screened Heated Swimming Pool'),
              ( 134, 'en-US', 'Swimming Pool'),
              ( 135, 'en-US', 'Jacuzzi'),
              ( 136, 'en-US', 'Parking'),
              ( 137, 'en-US', 'Covered Parking'),
              ( 138, 'en-US', 'Garage Parking'),
              ( 139, 'en-US', 'Gated Underground Parking'),
              ( 140, 'en-US', 'Heated Underground Parking'),
              ( 141, 'en-US', 'WiFi in Common Areas'),
              ( 142, 'en-US', 'Laundry Facilities'),
              ( 143, 'en-US', 'Washer and Dryer'),
              ( 144, 'en-US', 'Trash Chutes'),
              ( 145, 'en-US', 'Community Fireplace'),
              ( 146, 'en-US', 'Locked Mailboxes'),
              ( 147, 'en-US', 'Safety Rails'),
              ( 148, 'en-US', 'Smoke Alarm and Sprinkler System'),
              ( 149, 'en-US', 'Pets Welcome'),
              ( 150, 'en-US', 'Renters Liability Insurance Program'),
              ( 151, 'en-US', 'Wheelchair Accessible'),
              ( 152, 'en-US', 'Cottages'),
              ( 153, 'en-US', 'Three Chef Prepared Meals Daily'),
              ( 154, 'en-US', 'Full Calendar of Enriching Activities'),
              ( 155, 'en-US', 'Complimentary Scheduled Transportation'),
              ( 156, 'en-US', 'Weekly Housekeeping'),
              ( 157, 'en-US', 'Light Linen Service'),
              ( 158, 'en-US', 'Lively Mobile Plus Personal Emergency Response Device'),
              ( 159, 'en-US', 'Maintenance'),
              ( 160, 'en-US', 'Most Utilities Included'),
              ( 161, 'en-US', 'Exclusive Travel and Stay Program'),
              ( 162, 'en-US', 'Personal Emergency Response Device'),
              ( 163, 'en-US', 'Full Kitchen or Kitchenette'),
              ( 164, 'en-US', 'Guest Suite'),

              -- Community Attribute Icon Alt Text
              ( 165, 'en-US', 'Icon that represents food being served'),
              ( 166, 'en-US', 'Icon that represents food being served'),
              ( 167, 'en-US', 'Icon of a burger'),
              ( 168, 'en-US', 'Icon of two wine glasses together'),
              ( 169, 'en-US', 'Icon of Beer Mug'),
              ( 170, 'en-US', 'Icon of two chairs at a table with a glass of wine on top'),
              ( 171, 'en-US', 'Icon of Beer Mug'),
              ( 172, 'en-US', 'Icon of a sauna heat stone'),
              ( 173, 'en-US', 'Icon of a Swimming Pool Ladder'),
              ( 174, 'en-US', 'Icon of a Swimming Pool Ladder'),
              ( 175, 'en-US', 'Icon of a Swimming Pool Ladder'),
              ( 176, 'en-US', 'Icon of a car'),
              ( 177, 'en-US', 'Icon of a car'),
              ( 178, 'en-US', 'Icon of a car'),
              ( 179, 'en-US', 'Icon of a rose'),
              ( 180, 'en-US', 'Icon of a single person eating at a table'),
              ( 181, 'en-US', 'Icon of a fireplace'),
              ( 182, 'en-US', 'Icon of a barbecue grill'),
              ( 183, 'en-US', 'Icon of an outdoor walking path in the woods'),
              ( 184, 'en-US', 'Icon of a beach lounge bed underneath the sun'),
              ( 185, 'en-US', 'Icon of a golf flag inside of a hole'),
              ( 186, 'en-US', 'Icon of a plant in the ground'),
              ( 187, 'en-US', 'Icon of a hand pointing at an open book'),
              ( 188, 'en-US', 'Icon of a bookcase'),
              ( 189, 'en-US', 'Icon that represents entertainment media such as  music or videos'),
              ( 190, 'en-US', 'Icon of a movie camera'),
              ( 191, 'en-US', 'Icon of fitness dumbell weights'),
              ( 192, 'en-US', 'Icon of a person lifting another person''s leg'),
              ( 193, 'en-US', 'Icon of a bathroom hairdryer'),
              ( 194, 'en-US', 'Icon of a lotus flower'),
              ( 195, 'en-US', 'Icon of a stethoscope'),
              ( 196, 'en-US', 'Icon of a market shop'),
              ( 197, 'en-US', 'Icon of a ping pong paddle'),
              ( 198, 'en-US', 'Icon of a computer monitor'),
              ( 199, 'en-US', 'Icon of Wifi Signal'),
              ( 200, 'en-US', 'Icon of Wifi Signal'),
              ( 201, 'en-US', 'Icon that represents 3 boxes inside of a warehouse'),
              ( 202, 'en-US', 'Icon of a pawprint'),
              ( 203, 'en-US', 'Icon that represents 24 Hours'),
              ( 204, 'en-US', 'Icon of a human head and brain'),
              ( 205, 'en-US', 'Icon of a headset with a microphone'),
              ( 206, 'en-US', 'Icon of a Ringing Alarm Bell'),
              ( 207, 'en-US', 'Icon of a guitar and a baseball bat'),
              ( 208, 'en-US', 'Icon of asian rice bowl'),
              ( 209, 'en-US', 'Icon of bread with cancel circle'),
              ( 210, 'en-US', 'Icon of a leaf that represents vegan food'),
              ( 211, 'en-US', 'Icon of a Jewish Hexagram'),
              ( 212, 'en-US', 'Icon of two seasoning bottles'),
              ( 213, 'en-US', 'Icon that represents food being served'),
              ( 214, 'en-US', 'Icon that represents food being served'),
              ( 215, 'en-US', 'Icon that represents food being served'),
              ( 216, 'en-US', 'Icon that represents food being served'),
              ( 217, 'en-US', 'Icon that represents food being served'),
              ( 218, 'en-US', 'Icon of cleaning spray bottle'),
              ( 219, 'en-US', 'Icon of a iron'),
              ( 220, 'en-US', 'Icon of fitness dumbell weights'),
              ( 221, 'en-US', 'Icon of a person lifting another person''s leg'),
              ( 222, 'en-US', 'Icon of a newspaper'),
              ( 223, 'en-US', 'Icon of a transporation vehicle'),
              ( 224, 'en-US', 'Icon of a transporation vehicle'),
              ( 225, 'en-US', 'Icon of a transporation vehicle'),
              ( 226, 'en-US', 'Icon of a transporation vehicle'),
              ( 227, 'en-US', 'Icon of a transporation vehicle'),
              ( 228, 'en-US', 'Icon of a transporation vehicle'),
              ( 229, 'en-US', 'Icon of a transporation vehicle'),
              ( 230, 'en-US', 'Icon of four hands holding one hand in the shape of a square'),
              ( 231, 'en-US', 'Icon of a person lifting another person''s leg'),
              ( 232, 'en-US', 'Icon of a Peace Sign'),
              ( 233, 'en-US', 'Icon of a smart lock'),
              ( 234, 'en-US', 'Icon of a thermometer'),
              ( 235, 'en-US', 'Icon of a modern, double sofa'),
              ( 236, 'en-US', 'Icon of an oven'),
              ( 237, 'en-US', 'Icon of an oven'),
              ( 238, 'en-US', 'Icon of an oven'),
              ( 239, 'en-US', 'Icon of a microwave'),
              ( 240, 'en-US', 'Icon of a refridgerator'),
              ( 241, 'en-US', 'Icon of a balcony'),
              ( 242, 'en-US', 'Icon of a closet dresser and hanger'),
              ( 243, 'en-US', 'Icon of a bathroom shower'),
              ( 244, 'en-US', 'Icon of a laundry machine'),
              ( 245, 'en-US', 'Icon of a laundry machine'),
              ( 246, 'en-US', 'Icon of a laundry machine'),
              ( 247, 'en-US', 'Icon of a laundry machine'),
              ( 248, 'en-US', 'Icon of a flat screen tv'),
              ( 249, 'en-US', 'Icon of a shining lightbult'),
              ( 250, 'en-US', 'Icon of a wrench'),
              ( 251, 'en-US', 'Icon of cleaning spray bottle'),
              ( 252, 'en-US', 'Icon of a iron'),
              ( 253, 'en-US', 'oven'),
              ( 254, 'en-US', 'oven'),
              ( 255, 'en-US', 'fridge'),
              ( 256, 'en-US', 'balcony'),
              ( 257, 'en-US', 'laundry'),
              ( 258, 'en-US', 'laundry'),
              ( 259, 'en-US', 'hanger'),
              ( 260, 'en-US', 'shower'),
              ( 261, 'en-US', 'wifi'),
              ( 262, 'en-US', 'tv'),
              ( 263, 'en-US', 'phone'),
              ( 264, 'en-US', 'cleaning-vacuum'),
              ( 265, 'en-US', 'hvac'),
              ( 266, 'en-US', 'hvac'),
              ( 267, 'en-US', 'wheelchair'),
              ( 268, 'en-US', 'restaurant'),
              ( 269, 'en-US', 'restaurant'),
              ( 270, 'en-US', 'patio'),
              ( 271, 'en-US', 'ice-cream'),
              ( 272, 'en-US', 'kitchen'),
              ( 273, 'en-US', 'hair-dryer'),
              ( 274, 'en-US', 'spa-lotus'),
              ( 275, 'en-US', 'spa-lotus'),
              ( 276, 'en-US', 'fitness'),
              ( 277, 'en-US', 'fitness'),
              ( 278, 'en-US', 'chapel'),
              ( 279, 'en-US', 'camera'),
              ( 280, 'en-US', 'smart-tv'),
              ( 281, 'en-US', 'armchair'),
              ( 282, 'en-US', 'ping-pong'),
              ( 283, 'en-US', 'ping-pong'),
              ( 284, 'en-US', 'pool-table'),
              ( 285, 'en-US', 'library'),
              ( 286, 'en-US', 'music'),
              ( 287, 'en-US', 'screen'),
              ( 288, 'en-US', 'shop'),
              ( 289, 'en-US', 'shop'),
              ( 290, 'en-US', 'rose'),
              ( 291, 'en-US', 'plant'),
              ( 292, 'en-US', 'sunbed'),
              ( 293, 'en-US', 'landscape'),
              ( 294, 'en-US', 'koi-pond'),
              ( 295, 'en-US', 'swimming-pool'),
              ( 296, 'en-US', 'swimming-pool'),
              ( 297, 'en-US', 'swimming-pool'),
              ( 298, 'en-US', 'swimming-pool'),
              ( 299, 'en-US', 'sauna'),
              ( 300, 'en-US', 'car'),
              ( 301, 'en-US', 'car'),
              ( 302, 'en-US', 'car'),
              ( 303, 'en-US', 'car'),
              ( 304, 'en-US', 'car'),
              ( 305, 'en-US', 'wifi'),
              ( 306, 'en-US', 'laundry'),
              ( 307, 'en-US', 'laundry'),
              ( 308, 'en-US', 'trash'),
              ( 309, 'en-US', 'fireplace'),
              ( 310, 'en-US', 'mailbox'),
              ( 311, 'en-US', 'safety-rails'),
              ( 312, 'en-US', 'fire-extinguisher'),
              ( 313, 'en-US', 'pets'),
              ( 314, 'en-US', 'document'),
              ( 315, 'en-US', 'wheelchair'),
              ( 316, 'en-US', 'bedroom'),
              ( 317, 'en-US', 'room-service'),
              ( 318, 'en-US', 'calendar'),
              ( 319, 'en-US', 'bus'),
              ( 320, 'en-US', 'cleaning-spray'),
              ( 321, 'en-US', 'laundry-iron'),
              ( 322, 'en-US', 'mouse'),
              ( 323, 'en-US', 'wrench'),
              ( 324, 'en-US', 'bulb'),
              ( 325, 'en-US', 'travel'),
              ( 326, 'en-US', 'mouse'),
              ( 327, 'en-US', 'oven'),
              ( 328, 'en-US', 'bedroom'),
              ( 329, 'en-US', 'Restaurant with Table Service'),
              ( 330, 'en-US', 'Bistro'),
              ( 331, 'en-US', 'Grille'),
              ( 332, 'en-US', 'Cocktail Lounge'),
              ( 333, 'en-US', 'Pub'),
              ( 334, 'en-US', 'Private Dining Room'),
              ( 335, 'en-US', 'Sports Lounge'),
              ( 336, 'en-US', 'Hot Tub'),
              ( 337, 'en-US', 'Indoor Swimming Pool'),
              ( 338, 'en-US', 'Outdoor Swimming Pool'),
              ( 339, 'en-US', 'Off-Site Pool Privileges'),
              ( 340, 'en-US', 'Covered Parking'),
              ( 341, 'en-US', 'Parking Garage'),
              ( 342, 'en-US', 'Parking'),
              ( 343, 'en-US', 'Courtyard'),
              ( 344, 'en-US', 'Outdoor Dining Space'),
              ( 345, 'en-US', 'Outdoor Fireplace'),
              ( 346, 'en-US', 'Outdoor Grill'),
              ( 347, 'en-US', 'Walking Path'),
              ( 348, 'en-US', 'Patio'),
              ( 349, 'en-US', 'Putting Green'),
              ( 350, 'en-US', 'Resident Garden'),
              ( 351, 'en-US', 'Cognitive Learning Center'),
              ( 352, 'en-US', 'Library'),
              ( 353, 'en-US', 'Media Room'),
              ( 354, 'en-US', 'Movie Theater'),
              ( 355, 'en-US', 'Fitness Center'),
              ( 356, 'en-US', 'Physical Therapy Center'),
              ( 357, 'en-US', 'Salon'),
              ( 358, 'en-US', 'Salon & Spa'),
              ( 359, 'en-US', 'On-Site Physician Office Space'),
              ( 360, 'en-US', 'On-Site Sundries Shop'),
              ( 361, 'en-US', 'Game Room'),
              ( 362, 'en-US', 'Computers'),
              ( 363, 'en-US', 'Wi-Fi in Common Areas'),
              ( 364, 'en-US', 'Wi-Fi in Apartments'),
              ( 365, 'en-US', 'Storage Units Available'),
              ( 366, 'en-US', 'Pet-Friendly Environment'),
              ( 367, 'en-US', '24-Hour Staff'),
              ( 368, 'en-US', 'Alzheimer''s and Dementia Support Group'),
              ( 369, 'en-US', 'Concierge Service'),
              ( 370, 'en-US', 'Emergency Alert System'),
              ( 371, 'en-US', 'Daily Educational, Social, Cultural, and Fitness Opportunities'),
              ( 372, 'en-US', 'Locally-Inspired Cuisine'),
              ( 373, 'en-US', 'Gluten-Free Meals'),
              ( 374, 'en-US', 'Vegetarian Options'),
              ( 375, 'en-US', 'Kosher Meals'),
              ( 376, 'en-US', 'Low-Sodium Meals'),
              ( 377, 'en-US', '3 Chef-Prepared Meals Per Day'),
              ( 378, 'en-US', '3 Chef-Prepared Meals Per Day - Assisted Living'),
              ( 379, 'en-US', '2 Chef-Prepared Meals Per Day - Assisted Living'),
              ( 380, 'en-US', '2 Chef-Prepared Meals Per Day - Independent Living'),
              ( 381, 'en-US', '1 Chef-Prepared Meal Per Day - Independent Living'),
              ( 382, 'en-US', 'Housekeeping and Linen Service'),
              ( 383, 'en-US', 'Community Laundry Service'),
              ( 384, 'en-US', 'Fitness Trainer'),
              ( 385, 'en-US', 'Massage Therapy'),
              ( 386, 'en-US', 'Newspaper Delivery'),
              ( 387, 'en-US', 'Scheduled Bus and Sedan Transportation'),
              ( 388, 'en-US', 'Scheduled Sedan Transportation'),
              ( 389, 'en-US', 'Scheduled Bus Transportation'),
              ( 390, 'en-US', 'Scheduled Van Transportation'),
              ( 391, 'en-US', 'Scheduled Sedan and Van Transportation'),
              ( 392, 'en-US', 'Scheduled Bus and Van Transportation'),
              ( 393, 'en-US', 'Scheduled Bus, Van, and Sedan Transportation'),
              ( 394, 'en-US', 'Volunteer Programs'),
              ( 395, 'en-US', 'On-Site Physical Therapy / Occupational Therapy'),
              ( 396, 'en-US', 'On-Site Worship Services'),
              ( 397, 'en-US', 'Electronic Key Entry'),
              ( 398, 'en-US', 'Individual Thermostat Control'),
              ( 399, 'en-US', 'Furnished Apartments Available'),
              ( 400, 'en-US', 'Fully-Equipped Kitchen'),
              ( 401, 'en-US', 'Kitchen or Kitchenette'),
              ( 402, 'en-US', 'Kitchenette'),
              ( 403, 'en-US', 'Microwave'),
              ( 404, 'en-US', 'Refrigerator'),
              ( 405, 'en-US', 'Balcony or Patio - Select Apartments'),
              ( 406, 'en-US', 'Walk-In Closet'),
              ( 407, 'en-US', 'Walk-In Shower'),
              ( 408, 'en-US', 'Washer and Dryer - Select Apartments'),
              ( 409, 'en-US', 'Washer and Dryer Hookups - Select Apartments'),
              ( 410, 'en-US', 'Washer and Dryer'),
              ( 411, 'en-US', 'Washer and Dryer - Independent Living'),
              ( 412, 'en-US', 'Cable TV'),
              ( 413, 'en-US', 'Utilities Included'),
              ( 414, 'en-US', 'Apartment Maintenance'),
              ( 415, 'en-US', 'Housekeeping and Linen Service'),
              ( 416, 'en-US', 'Personal Laundry Service'),
              ( 417, 'en-US', 'Full Kitchen in Units'),
              ( 418, 'en-US', 'Kitchenette in Units'),
              ( 419, 'en-US', 'Refrigerator'),
              ( 420, 'en-US', 'Patio or Balcony'),
              ( 421, 'en-US', 'Washer and Dryer'),
              ( 422, 'en-US', 'Washer and Dryer Hookups'),
              ( 423, 'en-US', 'Walk-in Closet'),
              ( 424, 'en-US', 'Walk-in Tub'),
              ( 425, 'en-US', 'WiFi in Apartments'),
              ( 426, 'en-US', 'Basic Cable TV'),
              ( 427, 'en-US', 'Telephone Hookups'),
              ( 428, 'en-US', 'Carpet and Window Treatments'),
              ( 429, 'en-US', 'Individually Controlled Heating and Air Conditioning'),
              ( 430, 'en-US', 'Individually controlled HVAC units'),
              ( 431, 'en-US', 'Wheelchair Accessible Units'),
              ( 432, 'en-US', 'Private Dining Room'),
              ( 433, 'en-US', 'Bistro Area'),
              ( 434, 'en-US', 'Patio Dining'),
              ( 435, 'en-US', 'Ice Cream Parlor'),
              ( 436, 'en-US', 'Resident Kitchen'),
              ( 437, 'en-US', 'Barber/Beauty Salon'),
              ( 438, 'en-US', 'Spa Services'),
              ( 439, 'en-US', 'Sauna'),
              ( 440, 'en-US', 'Gym'),
              ( 441, 'en-US', 'Fitness Equipment'),
              ( 442, 'en-US', 'Chapel'),
              ( 443, 'en-US', 'Theater'),
              ( 444, 'en-US', 'Large Screen TV Lounge'),
              ( 445, 'en-US', 'Lounge Area'),
              ( 446, 'en-US', 'Activity Room'),
              ( 447, 'en-US', 'Game Room'),
              ( 448, 'en-US', 'Billiard Lounge'),
              ( 449, 'en-US', 'Library'),
              ( 450, 'en-US', 'Music Room'),
              ( 451, 'en-US', 'Computer Room with Internet Access'),
              ( 452, 'en-US', 'Country Store'),
              ( 453, 'en-US', 'Gift Shop'),
              ( 454, 'en-US', 'Community Grounds'),
              ( 455, 'en-US', 'Garden'),
              ( 456, 'en-US', 'Patio Area'),
              ( 457, 'en-US', 'Walking Paths'),
              ( 458, 'en-US', 'Koi Pond'),
              ( 459, 'en-US', 'Outdoor Swimming Pool'),
              ( 460, 'en-US', 'Poolside Clubhouse'),
              ( 461, 'en-US', 'Screened Heated Swimming Pool'),
              ( 462, 'en-US', 'Swimming Pool'),
              ( 463, 'en-US', 'Jacuzzi'),
              ( 464, 'en-US', 'Parking'),
              ( 465, 'en-US', 'Covered Parking'),
              ( 466, 'en-US', 'Garage Parking'),
              ( 467, 'en-US', 'Gated Underground Parking'),
              ( 468, 'en-US', 'Heated Underground Parking'),
              ( 469, 'en-US', 'WiFi in Common Areas'),
              ( 470, 'en-US', 'Laundry Facilities'),
              ( 471, 'en-US', 'Washer and Dryer'),
              ( 472, 'en-US', 'Trash Chutes'),
              ( 473, 'en-US', 'Community Fireplace'),
              ( 474, 'en-US', 'Locked Mailboxes'),
              ( 475, 'en-US', 'Safety Rails'),
              ( 476, 'en-US', 'Smoke Alarm and Sprinkler System'),
              ( 477, 'en-US', 'Pets Welcome'),
              ( 478, 'en-US', 'Renters Liability Insurance Program'),
              ( 479, 'en-US', 'Wheelchair Accessible'),
              ( 480, 'en-US', 'Cottages'),
              ( 481, 'en-US', 'Three Chef Prepared Meals Daily'),
              ( 482, 'en-US', 'Full Calendar of Enriching Activities'),
              ( 483, 'en-US', 'Complimentary Scheduled Transportation'),
              ( 484, 'en-US', 'Weekly Housekeeping'),
              ( 485, 'en-US', 'Light Linen Service'),
              ( 486, 'en-US', 'Lively Mobile Plus Personal Emergency Response Device'),
              ( 487, 'en-US', 'Maintenance'),
              ( 488, 'en-US', 'Most Utilities Included'),
              ( 489, 'en-US', 'Exclusive Travel and Stay Program'),
              ( 490, 'en-US', 'Personal Emergency Response Device'),
              ( 491, 'en-US', 'Full Kitchen or Kitchenette'),
              ( 492, 'en-US', 'Guest Suite'),
              ( 493, 'en-US', 'Northstar Moon Over Nowhere features outdoor patios and balconies with apartments and villas within our community.'),
              ( 494, 'en-US', 'Northstar Moon Over Nowhere features outdoor patios and balconies with apartments and villas within our community.'),
              ( 495, 'en-US', 'Gardens in the courtyard, with cozy seating nestled in shady corners, offer some respite or a great conversation spot to make new friends.'),
              ( 496, 'en-US', 'Gardens in the courtyard, with cozy seating nestled in shady corners, offer some respite or a great conversation spot to make new friends.'),
              ( 497, 'en-US', 'Northstar Moon Over Nowhere''s lobby welcomes you to this Spanish-styled residence with shimmering wood supports and beautifully tiled floors.'),
              ( 498, 'en-US', 'Northstar Moon Over Nowhere''s lobby welcomes you to this Spanish-styled residence with shimmering wood supports and beautifully tiled floors.'),
              ( 499, 'en-US', 'The game room sets you up for a round of Dominoes, Scrabble or card tournament, which offers easy access to our on-site sundries shop.'),
              ( 500, 'en-US', 'The game room sets you up for a round of Dominoes, Scrabble or card tournament, which offers easy access to our on-site sundries shop.'),
              ( 501, 'en-US', 'Whether it''s tea time or time for a meal, this dining area is perfect to introduce family and neighbors or take a quick break from your active day.'),
              ( 502, 'en-US', 'Whether it''s tea time or time for a meal, this dining area is perfect to introduce family and neighbors or take a quick break from your active day.'),
              ( 503, 'en-US', 'Residents can enjoy spacious seating and beautiful weather on a typical day in the community.'),
              ( 504, 'en-US', 'Residents can enjoy spacious seating and beautiful weather on a typical day in the community.'),
              ( 505, 'en-US', 'Take a stroll with friends and loved ones through the communities beautiful courtyard.'),
              ( 506, 'en-US', 'Take a stroll with friends and loved ones through the communities beautiful courtyard.'),
              ( 507, 'en-US', 'Cool off in the outdoor pool as the summer sun dances across the beautiful community.'),
              ( 508, 'en-US', 'Cool off in the outdoor pool as the summer sun dances across the beautiful community.'),
              ( 509, 'en-US', 'Fireside smores are the perfect recipe for a lovely night at Northstar Homeowners Realty.'),
              ( 510, 'en-US', 'Fireside smores are the perfect recipe for a lovely night at Northstar Homeowners Realty.'),
              ( 511, 'en-US', 'Cook up a favorite meal poolside as the sun sets on another wonderful day at Northstar Homeowners Realty.'),
              ( 512, 'en-US', 'Cook up a favorite meal poolside as the sun sets on another wonderful day at Northstar Homeowners Realty.'),
              ( 513, 'en-US', 'Residents can kick back, relax and enjoy life on their own terms in the beautiful veranda.'),
              ( 514, 'en-US', 'Residents can kick back, relax and enjoy life on their own terms in the beautiful veranda.'),
              ( 515, 'en-US', 'Residents will experience southwestern architecture and classic elegance as they make their way through the community.'),
              ( 516, 'en-US', 'Residents will experience southwestern architecture and classic elegance as they make their way through the community.'),
              ( 517, 'en-US', 'Catch up on a favorite book or peruse the library for a next favorite gem.'),
              ( 518, 'en-US', 'Catch up on a favorite book or peruse the library for a next favorite gem.'),
              ( 519, 'en-US', 'Comfort is key at Northstar Homeowners Realty. Make sure to take time and enjoy the little things.'),
              ( 520, 'en-US', 'Comfort is key at Northstar Homeowners Realty. Make sure to take time and enjoy the little things.'),
              ( 521, 'en-US', 'Enjoy the warm hearth of the fire in Northstar Tower of Hope''s library. Start a new novel or study a new subject.'),
              ( 522, 'en-US', 'Enjoy the warm hearth of the fire in Northstar Tower of Hope''s library. Start a new novel or study a new subject.'),
              ( 523, 'en-US', 'Seating on the Northstar Tower of Hope porch invites conversation with friends.'),
              ( 524, 'en-US', 'Seating on the Northstar Tower of Hope porch invites conversation with friends.'),
              ( 525, 'en-US', 'Patio seating at Northstar Tower of Hope contributes to Northstar''s philosophy of bringing people together.'),
              ( 526, 'en-US', 'Patio seating at Northstar Tower of Hope contributes to Northstar''s philosophy of bringing people together.'),
              ( 527, 'en-US', 'Just inside the doors to the patio, you can experience a Topeka sunset and ready yourself for an evening of music or laughter with friends.'),
              ( 528, 'en-US', 'Just inside the doors to the patio, you can experience a Topeka sunset and ready yourself for an evening of music or laughter with friends.'),
              ( 529, 'en-US', 'Enjoy the warm hearth of the fire in Northstar Tower of Hope''s library. Start a new novel or study a new subject.'),
              ( 530, 'en-US', 'Enjoy the warm hearth of the fire in Northstar Tower of Hope''s library. Start a new novel or study a new subject.'),
              ( 531, 'en-US', 'The chefs and wait staff pay special attention to details when creating a memorable dining experience at Northstar Tower of Hope.'),
              ( 532, 'en-US', 'The chefs and wait staff pay special attention to details when creating a memorable dining experience at Northstar Tower of Hope.'),
              ( 533, 'en-US', 'Northstar Tower of Hope''s private dining room offers residents a space to entertain family and friends for a special occasion.'),
              ( 534, 'en-US', 'Northstar Tower of Hope''s private dining room offers residents a space to entertain family and friends for a special occasion.'),
              ( 535, 'en-US', 'The Northstar Tower of Hope dining room captures natural sunlight in this comfortably appointed dining venue with table service.'),
              ( 536, 'en-US', 'The Northstar Tower of Hope dining room captures natural sunlight in this comfortably appointed dining venue with table service.'),
              ( 537, 'en-US', 'Apartments at Northstar Tower of Hope offer well-designed, spacious living options with patio or balcony views.'),
              ( 538, 'en-US', 'Apartments at Northstar Tower of Hope offer well-designed, spacious living options with patio or balcony views.'),
              ( 539, 'en-US', 'Entrance to Northstar Exuberanch''s two-story independent senior living community with stately columns and expansive porches on each level.'),
              ( 540, 'en-US', 'Entrance to Northstar Exuberanch''s two-story independent senior living community with stately columns and expansive porches on each level.'),
              ( 541, 'en-US', 'Bright, flower-lined walking path with intimate patio seating at one end and a birdbath on the other.'),
              ( 542, 'en-US', 'Bright, flower-lined walking path with intimate patio seating at one end and a birdbath on the other.'),
              ( 543, 'en-US', 'Two large windows and two lamps brightly illuminate this nicely decorated, spacious studio apartment. Bedroom and dining area furniture are visible.'),
              ( 544, 'en-US', 'Two large windows and two lamps brightly illuminate this nicely decorated, spacious studio apartment. Bedroom and dining area furniture are visible.'),
              ( 545, 'en-US', 'Entertainment space with small seating area, television, piano and fish tank opens into another larger seating area.'),
              ( 546, 'en-US', 'Entertainment space with small seating area, television, piano and fish tank opens into another larger seating area.'),
              ( 547, 'en-US', 'Common sitting area with high ceilings, traditional wooden furniture and brightly colored upholstery.'),
              ( 548, 'en-US', 'Common sitting area with high ceilings, traditional wooden furniture and brightly colored upholstery.'),
              ( 549, 'en-US', 'Overhead lighting illuminates this large, open dining area. Ten wooden tables are visible, with four comfortable armchairs per table.'),
              ( 550, 'en-US', 'Overhead lighting illuminates this large, open dining area. Ten wooden tables are visible, with four comfortable armchairs per table.'),
              ( 551, 'en-US', 'Game room with a Bingo caller wheel, puzzles and gaming tables with comfortable seating. Beer, cocktails and snacks are set at some of the tables.'),
              ( 552, 'en-US', 'Game room with a Bingo caller wheel, puzzles and gaming tables with comfortable seating. Beer, cocktails and snacks are set at some of the tables.'),
              ( 553, 'en-US', 'TV viewing area decorated in shades of beige and brown with indoor greenery. Traditional couches, armchairs and tables of various sizes are visible.'),
              ( 554, 'en-US', 'TV viewing area decorated in shades of beige and brown with indoor greenery. Traditional couches, armchairs and tables of various sizes are visible.'),
              ( 555, 'en-US', 'Nestled in the foothills of the Santa Catalina Mountains in Tucson, AZ, Northstar Moon Over Nowhere offers senior living with stunning views, an active lifestyle, and convenient amenities and services.'),
              ( 556, 'en-US', 'Northstar Homeowners Realty is an exclusive independent living community in Arizona. From taco bike tours to scavenger hunts in a desert oasis, Tucson has wide array of fun activities to accompany your stay.'),
              ( 557, 'en-US', 'Nestled into the center of Tucson, AZ, with scenic mountain views, Northstar La Casa Grande is a vibrant independent living community. Experience a fulfilling lifestyle with new opportunities every day.'),
              ( 558, 'en-US', 'Located in Topeka and less than an hour from Kansas City, Northstar Tower of Hope is a welcoming campus with two communities: the West location offers independent and assisted living, and the East location offers assisted living and memory care.'),
              ( 559, 'en-US', 'Located just seven miles from downtown Knoxville on grounds surrounded by mature trees, Northstar Exuberanch is a vibrant independent living, assisted living and memory care community.'),
              ( 560, 'en-US', 'Located 23 miles from downtown Houston, this senior living community offers independent living, assisted living and memory care for older adults. Enjoy an active lifestyle in Spring, TX.'),
              ( 561, 'en-US', 'Northstar Moon Over Nowhere'),
              ( 562, 'en-US', 'Northstar Homeowners Realty'),
              ( 563, 'en-US', 'Northstar La Casa Grande'),
              ( 564, 'en-US', 'Northstar Tower of Hope'),
              ( 565, 'en-US', 'Northstar Exuberanch'),
              ( 566, 'en-US', 'Northstar Stone Ranch'))
AS SOURCE (ContentId,
           LanguageCultureCode,
           CopyText)
ON TARGET.ContentId = SOURCE.ContentId AND TARGET.LanguageCultureCode = SOURCE.LanguageCultureCode
WHEN MATCHED THEN UPDATE SET TARGET.CopyText  = SOURCE.CopyText
WHEN NOT MATCHED THEN INSERT (ContentId,
                              LanguageCultureCode,
                              CopyText)
                      VALUES (SOURCE.ContentId,
                              SOURCE.LanguageCultureCode,
                              SOURCE.CopyText);