:r .\Populate\Populate_WorldRegion.sql
:r .\Populate\Populate_Country.sql
:r .\Populate\Populate_Airline.sql
:r .\Populate\Populate_Airport.sql
:r .\Populate\Populate_AircraftType.sql
:r .\Populate\Populate_FlightSchedule.sql
:r .\Populate\Populate_FlightStatus.sql
:r .\Populate\Populate_CustomerFlightStatus.sql
:r .\Populate\Populate_CustomerFlightStatusToFlightStatus.sql