// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Prototype3.Models;

/// <summary>
/// Lookup table of the different types of aircraft in use by the tracked flights.
/// </summary>
public partial class AircraftType
{
    /// <summary>
    /// The code for the aircraft type.
    /// </summary>
    public string AircraftTypeCode { get; set; }

    /// <summary>
    /// The name of the aircraft type.
    /// </summary>
    public string AircraftTypeName { get; set; }

    /// <summary>
    /// The manufacturer of the aircraft type.
    /// </summary>
    public string Manufacturer { get; set; }

    /// <summary>
    /// The taxi speed for the aircraft type in kilometers per hour (KPH).
    /// </summary>
    public int TaxiSpeed { get; set; }

    /// <summary>
    /// The lower bound of the rotational speed range for the aircraft type in kilometers per hour (KPH).
    /// </summary>
    public int RotationalSpeedLower { get; set; }

    /// <summary>
    /// The upper bound of the rotational speed range for the aircraft type in kilometers per hour (KPH).
    /// </summary>
    public int RotationalSpeedUpper { get; set; }

    /// <summary>
    /// The lower bound of the initial climb speed range for the aircraft type in kilometers per hour (KPH).
    /// </summary>
    public int InitialClimbSpeedLower { get; set; }

    /// <summary>
    /// The upper bound of the initial climb speed range for the aircraft type. in kilometers per hour (KPH)
    /// </summary>
    public int InitialClimbSpeedUpper { get; set; }

    /// <summary>
    /// The lower bound of the climb speed range for the aircraft type in kilometers per hour (KPH).
    /// </summary>
    public int ClimbSpeedLower { get; set; }

    /// <summary>
    /// The upper bound of the climb speed range for the aircraft type in kilometers per hour (KPH).
    /// </summary>
    public int ClimbSpeedUpper { get; set; }

    /// <summary>
    /// The lower bound of the cruise speed range for the aircraft type in kilometers per hour (KPH).
    /// </summary>
    public int CruiseSpeedLower { get; set; }

    /// <summary>
    /// The upper bound of the cruise speed range for the aircraft type in kilometers per hour (KPH).
    /// </summary>
    public int CruiseSpeedUpper { get; set; }

    /// <summary>
    /// The lower bound of the descent speed range for the aircraft type in kilometers per hour (KPH).
    /// </summary>
    public int DescentSpeedLower { get; set; }

    /// <summary>
    /// The upper bound of the descent speed range for the aircraft type in kilometers per hour (KPH).
    /// </summary>
    public int DescentSpeedUpper { get; set; }

    /// <summary>
    /// The lower bound of the approach speed range for the aircraft type in kilometers per hour (KPH).
    /// </summary>
    public int ApproachSpeedLower { get; set; }

    /// <summary>
    /// The upper bound of the approach speed range for the aircraft type in kilometers per hour (KPH).
    /// </summary>
    public int ApproachSpeedUpper { get; set; }

    /// <summary>
    /// The lower bound of the landing speed range for the aircraft type in kilometers per hour (KPH).
    /// </summary>
    public int LandingSpeedLower { get; set; }

    /// <summary>
    /// The upper bound of the landing speed range for the aircraft type in kilometers per hour (KPH).
    /// </summary>
    public int LandingSpeedUpper { get; set; }

    /// <summary>
    /// The lower bound of the initial climb altitude range for the aircraft type in meters (m).
    /// </summary>
    public int InitialClimbAltitudeLower { get; set; }

    /// <summary>
    /// The upper bound of the initial climb altitude range for the aircraft type in meters (m).
    /// </summary>
    public int InitialClimbAltitudeUpper { get; set; }

    /// <summary>
    /// The lower bound of the cruise altitude range for the aircraft type in meters (m).
    /// </summary>
    public int CruiseAltitudeLower { get; set; }

    /// <summary>
    /// The upper bound of the cruise altitude range for the aircraft type in meters (m).
    /// </summary>
    public int CruiseAltitudeUpper { get; set; }

    /// <summary>
    /// The lower bound of the approach altitude range for the aircraft type in meters (m).
    /// </summary>
    public int ApproachAltitudeLower { get; set; }

    /// <summary>
    /// The upper bound of the approach altitude range for the aircraft type in meters (m).
    /// </summary>
    public int ApproachAltitudeUpper { get; set; }

    public virtual ICollection<FlightPlan> FlightPlans { get; set; } = new List<FlightPlan>();

    public virtual ICollection<FlightSchedule> FlightSchedules { get; set; } = new List<FlightSchedule>();

    public virtual ICollection<ScheduledFlight> ScheduledFlights { get; set; } = new List<ScheduledFlight>();
}