// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Prototype3.Models;

/// <summary>
/// Lookup table representing the airlines supported by the system.
/// </summary>
public partial class Airline
{
    /// <summary>
    /// The IATA code for the airline.
    /// </summary>
    public string Iatacode { get; set; }

    /// <summary>
    /// The ICAO code for the airline.
    /// </summary>
    public string Icaocode { get; set; }

    /// <summary>
    /// The name of the airline.
    /// </summary>
    public string AirlineName { get; set; }

    /// <summary>
    /// The callsign for the airline.
    /// </summary>
    public string Callsign { get; set; }

    /// <summary>
    /// The code of the country where the airline is headquatered.
    /// </summary>
    public string CountryCode { get; set; }

    /// <summary>
    /// Flag indicating whether the airline is active within the system.
    /// </summary>
    public bool IsActive { get; set; }

    public virtual Country CountryCodeNavigation { get; set; }

    public virtual ICollection<FlightPlan> FlightPlans { get; set; } = new List<FlightPlan>();

    public virtual ICollection<FlightSchedule> FlightSchedules { get; set; } = new List<FlightSchedule>();
}