// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Prototype3.Models;

/// <summary>
/// Lookup table of the different status of a customer&apos;s flight.
/// </summary>
public partial class CustomerFlightStatus
{
    /// <summary>
    /// The code for the customer&apos;s flight status.
    /// </summary>
    public string CustomerFlightStatusCode { get; set; }

    /// <summary>
    /// The name of the customer&apos;s flight status.
    /// </summary>
    public string CustomerFlightStatusName { get; set; }

    /// <summary>
    /// The description of the customer&apos;s flight status.
    /// </summary>
    public string CustomerFlightStatusDescription { get; set; }

    /// <summary>
    /// The code of the associated flight status.
    /// </summary>
    public string AssociatedFlightStatusCode { get; set; }

    public virtual FlightStatus AssociatedFlightStatusCodeNavigation { get; set; }
}