// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Prototype3.Models;

/// <summary>
/// Lookup table representing the scheduled flight.
/// </summary>
public partial class ScheduledFlight
{
    /// <summary>
    /// Identifier of the scheduled flight.
    /// </summary>
    public int ScheuledFlightId { get; set; }

    /// <summary>
    /// The IATA code of the airport where the flight departs.
    /// </summary>
    public string OriginAirportCode { get; set; }

    /// <summary>
    /// The IATA code of the airport where the flight arrives.
    /// </summary>
    public string DestinationAirportCode { get; set; }

    /// <summary>
    /// The type of aircraft used for the flight.
    /// </summary>
    public string AircraftTypeCode { get; set; }

    /// <summary>
    /// The current status of the flight.
    /// </summary>
    public string CurrentStatusCode { get; set; }

    public virtual AircraftType AircraftTypeCodeNavigation { get; set; }

    public virtual Airport DestinationAirportCodeNavigation { get; set; }

    public virtual Airport OriginAirportCodeNavigation { get; set; }
}